(declare-datatypes ((_enum_0 0)) (((INF) (SEC) (MSEC))))
(declare-datatypes ((_tuple_0 0)) (((_tuple_0 (__f1 Int) (__f2 _enum_0)))))
(declare-datatypes ((_tuple_1 0)) (((_tuple_1 (__f1 _tuple_0) (__f2 Int)))))
(declare-datatypes ((_enum_1 0)) (((NULL) (A1) (A2) (B1) (C1))))
(declare-datatypes ((_tuple_2 0)) (((_tuple_2 (__f1 _enum_1) (__f2 _tuple_1)))))
(declare-datatypes ((_tuple_3 0)) (((_tuple_3 (__f1 _tuple_2) (__f2 _tuple_2) (__f3 _tuple_2) (__f4 _tuple_2) (__f5 _tuple_2) (__f6 _tuple_2) (__f7 _tuple_2) (__f8 _tuple_2) (__f9 _tuple_2) (__f10 _tuple_2)))))
(declare-fun initial_2_trace_C () _tuple_3)
(declare-fun initial_1_trace_A () _tuple_3)
(declare-fun initial_3_trace_B () _tuple_3)
(assert (forall ((i Int))
  (! (let ((a!1 (ite (= i 9)
                     (__f10 initial_2_trace_C)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0)))))
     (let ((a!2 (ite (= i 6)
                     (__f7 initial_2_trace_C)
                     (ite (= i 7)
                          (__f8 initial_2_trace_C)
                          (ite (= i 8) (__f9 initial_2_trace_C) a!1)))))
     (let ((a!3 (ite (= i 3)
                     (__f4 initial_2_trace_C)
                     (ite (= i 4)
                          (__f5 initial_2_trace_C)
                          (ite (= i 5) (__f6 initial_2_trace_C) a!2)))))
     (let ((a!4 (ite (= i 0)
                     (__f1 initial_2_trace_C)
                     (ite (= i 1)
                          (__f2 initial_2_trace_C)
                          (ite (= i 2) (__f3 initial_2_trace_C) a!3)))))
     (let ((a!5 (>= (__f1 (__f1 (__f2 a!4))) 0)))
     (let ((a!6 (and a!5 (>= (__f2 (__f2 a!4)) 0))))
       (or (not (and (>= i 0) (<= i 9))) a!6)))))))
     :skolemid _skolem_0
     :qid _forall_0)))
(assert (forall ((k Int))
  (! (let ((a!1 (ite (= k 9)
                     (__f10 initial_2_trace_C)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0)))))
     (let ((a!2 (ite (= k 6)
                     (__f7 initial_2_trace_C)
                     (ite (= k 7)
                          (__f8 initial_2_trace_C)
                          (ite (= k 8) (__f9 initial_2_trace_C) a!1)))))
     (let ((a!3 (ite (= k 3)
                     (__f4 initial_2_trace_C)
                     (ite (= k 4)
                          (__f5 initial_2_trace_C)
                          (ite (= k 5) (__f6 initial_2_trace_C) a!2)))))
     (let ((a!4 (ite (= k 0)
                     (__f1 initial_2_trace_C)
                     (ite (= k 1)
                          (__f2 initial_2_trace_C)
                          (ite (= k 2) (__f3 initial_2_trace_C) a!3)))))
       (or (not (and (>= k 0) (<= k 9))) (= (__f1 a!4) NULL) (= (__f1 a!4) C1))))))
     :skolemid _skolem_1
     :qid _forall_1)))
(assert (forall ((i Int))
  (! (let ((a!1 (ite (= i 9)
                     (__f10 initial_1_trace_A)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0))))
           (a!6 (exists ((j Int))
                  (! (let ((a!1 (ite (= j 9)
                                     (__f10 initial_1_trace_A)
                                     (_tuple_2 NULL
                                               (_tuple_1 (_tuple_0 0 INF) 0))))
                           (a!5 (ite (= i 9)
                                     (__f10 initial_1_trace_A)
                                     (_tuple_2 NULL
                                               (_tuple_1 (_tuple_0 0 INF) 0)))))
                     (let ((a!2 (ite (= j 6)
                                     (__f7 initial_1_trace_A)
                                     (ite (= j 7)
                                          (__f8 initial_1_trace_A)
                                          (ite (= j 8)
                                               (__f9 initial_1_trace_A)
                                               a!1))))
                           (a!6 (ite (= i 6)
                                     (__f7 initial_1_trace_A)
                                     (ite (= i 7)
                                          (__f8 initial_1_trace_A)
                                          (ite (= i 8)
                                               (__f9 initial_1_trace_A)
                                               a!5)))))
                     (let ((a!3 (ite (= j 3)
                                     (__f4 initial_1_trace_A)
                                     (ite (= j 4)
                                          (__f5 initial_1_trace_A)
                                          (ite (= j 5)
                                               (__f6 initial_1_trace_A)
                                               a!2))))
                           (a!7 (ite (= i 3)
                                     (__f4 initial_1_trace_A)
                                     (ite (= i 4)
                                          (__f5 initial_1_trace_A)
                                          (ite (= i 5)
                                               (__f6 initial_1_trace_A)
                                               a!6)))))
                     (let ((a!4 (ite (= j 0)
                                     (__f1 initial_1_trace_A)
                                     (ite (= j 1)
                                          (__f2 initial_1_trace_A)
                                          (ite (= j 2)
                                               (__f3 initial_1_trace_A)
                                               a!3))))
                           (a!8 (ite (= i 0)
                                     (__f1 initial_1_trace_A)
                                     (ite (= i 1)
                                          (__f2 initial_1_trace_A)
                                          (ite (= i 2)
                                               (__f3 initial_1_trace_A)
                                               a!7)))))
                     (let ((a!9 (= (__f2 (__f1 (__f2 a!8))) INF))
                           (a!10 (= (__f2 (__f1 (__f2 a!8))) SEC))
                           (a!11 (* 1000 (__f1 (__f1 (__f2 a!8))))))
                     (let ((a!12 (__f1 (ite a!10
                                            (_tuple_0 a!11 MSEC)
                                            (__f1 (__f2 a!8))))))
                     (let ((a!13 (ite a!9
                                      (_tuple_1 (_tuple_0 0 INF) 0)
                                      (_tuple_1 (_tuple_0 (+ 5000 a!12) MSEC)
                                                (__f2 (__f2 a!8))))))
                       (and (= (__f1 a!4) A2) (= (__f2 a!4) a!13)))))))))
                     :skolemid _skolem_2
                     :qid _exists_0))))
     (let ((a!2 (ite (= i 6)
                     (__f7 initial_1_trace_A)
                     (ite (= i 7)
                          (__f8 initial_1_trace_A)
                          (ite (= i 8) (__f9 initial_1_trace_A) a!1)))))
     (let ((a!3 (ite (= i 3)
                     (__f4 initial_1_trace_A)
                     (ite (= i 4)
                          (__f5 initial_1_trace_A)
                          (ite (= i 5) (__f6 initial_1_trace_A) a!2)))))
     (let ((a!4 (ite (= i 0)
                     (__f1 initial_1_trace_A)
                     (ite (= i 1)
                          (__f2 initial_1_trace_A)
                          (ite (= i 2) (__f3 initial_1_trace_A) a!3)))))
     (let ((a!5 (not (and (= (__f1 a!4) A2) (not (<= 9 i))))))
       (or a!5 a!6))))))
     :skolemid _skolem_3
     :qid _forall_2)))
(assert (forall ((i Int))
  (! (let ((a!1 (ite (= i 9)
                     (__f10 initial_3_trace_B)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0))))
           (a!6 (exists ((j Int))
                  (! (let ((a!1 (ite (= j 9)
                                     (__f10 initial_2_trace_C)
                                     (_tuple_2 NULL
                                               (_tuple_1 (_tuple_0 0 INF) 0))))
                           (a!5 (ite (= i 9)
                                     (__f10 initial_3_trace_B)
                                     (_tuple_2 NULL
                                               (_tuple_1 (_tuple_0 0 INF) 0)))))
                     (let ((a!2 (ite (= j 6)
                                     (__f7 initial_2_trace_C)
                                     (ite (= j 7)
                                          (__f8 initial_2_trace_C)
                                          (ite (= j 8)
                                               (__f9 initial_2_trace_C)
                                               a!1))))
                           (a!6 (ite (= i 6)
                                     (__f7 initial_3_trace_B)
                                     (ite (= i 7)
                                          (__f8 initial_3_trace_B)
                                          (ite (= i 8)
                                               (__f9 initial_3_trace_B)
                                               a!5)))))
                     (let ((a!3 (ite (= j 3)
                                     (__f4 initial_2_trace_C)
                                     (ite (= j 4)
                                          (__f5 initial_2_trace_C)
                                          (ite (= j 5)
                                               (__f6 initial_2_trace_C)
                                               a!2))))
                           (a!7 (ite (= i 3)
                                     (__f4 initial_3_trace_B)
                                     (ite (= i 4)
                                          (__f5 initial_3_trace_B)
                                          (ite (= i 5)
                                               (__f6 initial_3_trace_B)
                                               a!6)))))
                     (let ((a!4 (ite (= j 0)
                                     (__f1 initial_2_trace_C)
                                     (ite (= j 1)
                                          (__f2 initial_2_trace_C)
                                          (ite (= j 2)
                                               (__f3 initial_2_trace_C)
                                               a!3))))
                           (a!8 (ite (= i 0)
                                     (__f1 initial_3_trace_B)
                                     (ite (= i 1)
                                          (__f2 initial_3_trace_B)
                                          (ite (= i 2)
                                               (__f3 initial_3_trace_B)
                                               a!7)))))
                     (let ((a!9 (= (__f2 (__f1 (__f2 a!8))) INF))
                           (a!10 (= (__f2 (__f1 (__f2 a!8))) SEC))
                           (a!11 (* 1000 (__f1 (__f1 (__f2 a!8))))))
                     (let ((a!12 (__f1 (ite a!10
                                            (_tuple_0 a!11 MSEC)
                                            (__f1 (__f2 a!8))))))
                     (let ((a!13 (ite a!9
                                      (_tuple_1 (_tuple_0 0 INF) 0)
                                      (_tuple_1 (_tuple_0 a!12 MSEC)
                                                (__f2 (__f2 a!8))))))
                       (and (= (__f1 a!4) C1) (= (__f2 a!4) a!13)))))))))
                     :skolemid _skolem_4
                     :qid _exists_1))))
     (let ((a!2 (ite (= i 6)
                     (__f7 initial_3_trace_B)
                     (ite (= i 7)
                          (__f8 initial_3_trace_B)
                          (ite (= i 8) (__f9 initial_3_trace_B) a!1)))))
     (let ((a!3 (ite (= i 3)
                     (__f4 initial_3_trace_B)
                     (ite (= i 4)
                          (__f5 initial_3_trace_B)
                          (ite (= i 5) (__f6 initial_3_trace_B) a!2)))))
     (let ((a!4 (ite (= i 0)
                     (__f1 initial_3_trace_B)
                     (ite (= i 1)
                          (__f2 initial_3_trace_B)
                          (ite (= i 2) (__f3 initial_3_trace_B) a!3)))))
     (let ((a!5 (not (and (= (__f1 a!4) B1) (not (<= 9 i))))))
       (or a!5 a!6))))))
     :skolemid _skolem_5
     :qid _forall_3)))
(assert (forall ((i Int) (j Int))
  (! (let ((a!1 (ite (= i 9)
                     (__f10 initial_2_trace_C)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0))))
           (a!5 (ite (= j 9)
                     (__f10 initial_2_trace_C)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0)))))
     (let ((a!2 (ite (= i 6)
                     (__f7 initial_2_trace_C)
                     (ite (= i 7)
                          (__f8 initial_2_trace_C)
                          (ite (= i 8) (__f9 initial_2_trace_C) a!1))))
           (a!6 (ite (= j 6)
                     (__f7 initial_2_trace_C)
                     (ite (= j 7)
                          (__f8 initial_2_trace_C)
                          (ite (= j 8) (__f9 initial_2_trace_C) a!5)))))
     (let ((a!3 (ite (= i 3)
                     (__f4 initial_2_trace_C)
                     (ite (= i 4)
                          (__f5 initial_2_trace_C)
                          (ite (= i 5) (__f6 initial_2_trace_C) a!2))))
           (a!7 (ite (= j 3)
                     (__f4 initial_2_trace_C)
                     (ite (= j 4)
                          (__f5 initial_2_trace_C)
                          (ite (= j 5) (__f6 initial_2_trace_C) a!6)))))
     (let ((a!4 (ite (= i 0)
                     (__f1 initial_2_trace_C)
                     (ite (= i 1)
                          (__f2 initial_2_trace_C)
                          (ite (= i 2) (__f3 initial_2_trace_C) a!3))))
           (a!8 (ite (= j 0)
                     (__f1 initial_2_trace_C)
                     (ite (= j 1)
                          (__f2 initial_2_trace_C)
                          (ite (= j 2) (__f3 initial_2_trace_C) a!7)))))
       (or (not (and (>= i 0) (<= i 9) (>= j 0) (<= j 9)))
           (not (= (__f1 a!4) (__f1 a!8)))
           (not (= (__f2 a!4) (__f2 a!8)))
           (= i j))))))
     :skolemid _skolem_6
     :qid _forall_4)))
(assert (forall ((i Int))
  (! (let ((a!1 (ite (= i 9)
                     (__f10 initial_1_trace_A)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0))))
           (a!6 (exists ((j Int))
                  (! (let ((a!1 (ite (= j 9)
                                     (__f10 initial_3_trace_B)
                                     (_tuple_2 NULL
                                               (_tuple_1 (_tuple_0 0 INF) 0))))
                           (a!5 (ite (= i 9)
                                     (__f10 initial_1_trace_A)
                                     (_tuple_2 NULL
                                               (_tuple_1 (_tuple_0 0 INF) 0)))))
                     (let ((a!2 (ite (= j 6)
                                     (__f7 initial_3_trace_B)
                                     (ite (= j 7)
                                          (__f8 initial_3_trace_B)
                                          (ite (= j 8)
                                               (__f9 initial_3_trace_B)
                                               a!1))))
                           (a!6 (ite (= i 6)
                                     (__f7 initial_1_trace_A)
                                     (ite (= i 7)
                                          (__f8 initial_1_trace_A)
                                          (ite (= i 8)
                                               (__f9 initial_1_trace_A)
                                               a!5)))))
                     (let ((a!3 (ite (= j 3)
                                     (__f4 initial_3_trace_B)
                                     (ite (= j 4)
                                          (__f5 initial_3_trace_B)
                                          (ite (= j 5)
                                               (__f6 initial_3_trace_B)
                                               a!2))))
                           (a!7 (ite (= i 3)
                                     (__f4 initial_1_trace_A)
                                     (ite (= i 4)
                                          (__f5 initial_1_trace_A)
                                          (ite (= i 5)
                                               (__f6 initial_1_trace_A)
                                               a!6)))))
                     (let ((a!4 (ite (= j 0)
                                     (__f1 initial_3_trace_B)
                                     (ite (= j 1)
                                          (__f2 initial_3_trace_B)
                                          (ite (= j 2)
                                               (__f3 initial_3_trace_B)
                                               a!3))))
                           (a!8 (ite (= i 0)
                                     (__f1 initial_1_trace_A)
                                     (ite (= i 1)
                                          (__f2 initial_1_trace_A)
                                          (ite (= i 2)
                                               (__f3 initial_1_trace_A)
                                               a!7)))))
                     (let ((a!9 (= (__f2 (__f1 (__f2 a!8))) INF))
                           (a!10 (= (__f2 (__f1 (__f2 a!8))) SEC))
                           (a!11 (* 1000 (__f1 (__f1 (__f2 a!8))))))
                     (let ((a!12 (__f1 (ite a!10
                                            (_tuple_0 a!11 MSEC)
                                            (__f1 (__f2 a!8))))))
                     (let ((a!13 (ite a!9
                                      (_tuple_1 (_tuple_0 0 INF) 0)
                                      (_tuple_1 (_tuple_0 a!12 MSEC)
                                                (__f2 (__f2 a!8))))))
                       (and (= (__f1 a!4) B1) (= (__f2 a!4) a!13)))))))))
                     :skolemid _skolem_7
                     :qid _exists_2))))
     (let ((a!2 (ite (= i 6)
                     (__f7 initial_1_trace_A)
                     (ite (= i 7)
                          (__f8 initial_1_trace_A)
                          (ite (= i 8) (__f9 initial_1_trace_A) a!1)))))
     (let ((a!3 (ite (= i 3)
                     (__f4 initial_1_trace_A)
                     (ite (= i 4)
                          (__f5 initial_1_trace_A)
                          (ite (= i 5) (__f6 initial_1_trace_A) a!2)))))
     (let ((a!4 (ite (= i 0)
                     (__f1 initial_1_trace_A)
                     (ite (= i 1)
                          (__f2 initial_1_trace_A)
                          (ite (= i 2) (__f3 initial_1_trace_A) a!3)))))
     (let ((a!5 (not (and (= (__f1 a!4) A2) (not (<= 9 i))))))
       (or a!5 a!6))))))
     :skolemid _skolem_8
     :qid _forall_5)))
(assert (forall ((i Int))
  (! (let ((a!1 (ite (= i 9)
                     (__f10 initial_1_trace_A)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0)))))
     (let ((a!2 (ite (= i 6)
                     (__f7 initial_1_trace_A)
                     (ite (= i 7)
                          (__f8 initial_1_trace_A)
                          (ite (= i 8) (__f9 initial_1_trace_A) a!1)))))
     (let ((a!3 (ite (= i 3)
                     (__f4 initial_1_trace_A)
                     (ite (= i 4)
                          (__f5 initial_1_trace_A)
                          (ite (= i 5) (__f6 initial_1_trace_A) a!2)))))
     (let ((a!4 (ite (= i 0)
                     (__f1 initial_1_trace_A)
                     (ite (= i 1)
                          (__f2 initial_1_trace_A)
                          (ite (= i 2) (__f3 initial_1_trace_A) a!3)))))
     (let ((a!5 (>= (__f1 (__f1 (__f2 a!4))) 0)))
     (let ((a!6 (and a!5 (>= (__f2 (__f2 a!4)) 0))))
       (or (not (and (>= i 0) (<= i 9))) a!6)))))))
     :skolemid _skolem_9
     :qid _forall_6)))
(assert (forall ((i Int) (j Int))
  (! (let ((a!1 (not (and (not (<= j i)) (>= i 0) (<= i 9) (>= j 0) (<= j 9))))
           (a!2 (ite (= i 9)
                     (__f10 initial_2_trace_C)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0))))
           (a!7 (ite (= j 9)
                     (__f10 initial_2_trace_C)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0)))))
     (let ((a!3 (ite (= i 6)
                     (__f7 initial_2_trace_C)
                     (ite (= i 7)
                          (__f8 initial_2_trace_C)
                          (ite (= i 8) (__f9 initial_2_trace_C) a!2))))
           (a!8 (ite (= j 6)
                     (__f7 initial_2_trace_C)
                     (ite (= j 7)
                          (__f8 initial_2_trace_C)
                          (ite (= j 8) (__f9 initial_2_trace_C) a!7)))))
     (let ((a!4 (ite (= i 3)
                     (__f4 initial_2_trace_C)
                     (ite (= i 4)
                          (__f5 initial_2_trace_C)
                          (ite (= i 5) (__f6 initial_2_trace_C) a!3))))
           (a!9 (ite (= j 3)
                     (__f4 initial_2_trace_C)
                     (ite (= j 4)
                          (__f5 initial_2_trace_C)
                          (ite (= j 5) (__f6 initial_2_trace_C) a!8)))))
     (let ((a!5 (ite (= i 0)
                     (__f1 initial_2_trace_C)
                     (ite (= i 1)
                          (__f2 initial_2_trace_C)
                          (ite (= i 2) (__f3 initial_2_trace_C) a!4))))
           (a!10 (ite (= j 0)
                      (__f1 initial_2_trace_C)
                      (ite (= j 1)
                           (__f2 initial_2_trace_C)
                           (ite (= j 2) (__f3 initial_2_trace_C) a!9)))))
     (let ((a!6 (= (__f2 (__f1 (__f2 a!5))) INF))
           (a!11 (= (__f2 (__f1 (__f2 a!10))) INF))
           (a!12 (= (__f2 (__f1 (__f2 a!5))) SEC))
           (a!13 (* 1000 (__f1 (__f1 (__f2 a!5)))))
           (a!14 (= (__f2 (__f1 (__f2 a!10))) SEC))
           (a!15 (* 1000 (__f1 (__f1 (__f2 a!10)))))
           (a!20 (not (<= (__f2 (__f2 a!5)) (__f2 (__f2 a!10))))))
     (let ((a!16 (= (ite a!12 (_tuple_0 a!13 MSEC) (__f1 (__f2 a!5)))
                    (ite a!14 (_tuple_0 a!15 MSEC) (__f1 (__f2 a!10)))))
           (a!18 (__f1 (ite a!12 (_tuple_0 a!13 MSEC) (__f1 (__f2 a!5)))))
           (a!19 (__f1 (ite a!14 (_tuple_0 a!15 MSEC) (__f1 (__f2 a!10))))))
     (let ((a!17 (and a!16 (= (__f2 (__f2 a!5)) (__f2 (__f2 a!10)))))
           (a!21 (not (or (and (not a!6) a!11)
                          (and (= a!18 a!19) a!20)
                          (not (<= a!18 a!19))))))
     (let ((a!22 (and a!21 (not (or (and a!6 a!11) a!17)))))
       (or a!1 (and a!6 a!11) a!17 a!22)))))))))
     :skolemid _skolem_10
     :qid _forall_7)))
(assert (forall ((i Int))
  (! (let ((a!1 (ite (= i 9)
                     (__f10 initial_2_trace_C)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0))))
           (a!6 (exists ((j Int))
                  (! (let ((a!1 (ite (= j 9)
                                     (__f10 initial_3_trace_B)
                                     (_tuple_2 NULL
                                               (_tuple_1 (_tuple_0 0 INF) 0))))
                           (a!5 (ite (= i 9)
                                     (__f10 initial_2_trace_C)
                                     (_tuple_2 NULL
                                               (_tuple_1 (_tuple_0 0 INF) 0)))))
                     (let ((a!2 (ite (= j 6)
                                     (__f7 initial_3_trace_B)
                                     (ite (= j 7)
                                          (__f8 initial_3_trace_B)
                                          (ite (= j 8)
                                               (__f9 initial_3_trace_B)
                                               a!1))))
                           (a!6 (ite (= i 6)
                                     (__f7 initial_2_trace_C)
                                     (ite (= i 7)
                                          (__f8 initial_2_trace_C)
                                          (ite (= i 8)
                                               (__f9 initial_2_trace_C)
                                               a!5)))))
                     (let ((a!3 (ite (= j 3)
                                     (__f4 initial_3_trace_B)
                                     (ite (= j 4)
                                          (__f5 initial_3_trace_B)
                                          (ite (= j 5)
                                               (__f6 initial_3_trace_B)
                                               a!2))))
                           (a!7 (ite (= i 3)
                                     (__f4 initial_2_trace_C)
                                     (ite (= i 4)
                                          (__f5 initial_2_trace_C)
                                          (ite (= i 5)
                                               (__f6 initial_2_trace_C)
                                               a!6)))))
                     (let ((a!4 (ite (= j 0)
                                     (__f1 initial_3_trace_B)
                                     (ite (= j 1)
                                          (__f2 initial_3_trace_B)
                                          (ite (= j 2)
                                               (__f3 initial_3_trace_B)
                                               a!3))))
                           (a!8 (ite (= i 0)
                                     (__f1 initial_2_trace_C)
                                     (ite (= i 1)
                                          (__f2 initial_2_trace_C)
                                          (ite (= i 2)
                                               (__f3 initial_2_trace_C)
                                               a!7)))))
                     (let ((a!9 (= (__f2 (__f1 (__f2 a!4))) INF))
                           (a!10 (= (__f2 (__f1 (__f2 a!4))) SEC))
                           (a!11 (* 1000 (__f1 (__f1 (__f2 a!4))))))
                     (let ((a!12 (__f1 (ite a!10
                                            (_tuple_0 a!11 MSEC)
                                            (__f1 (__f2 a!4))))))
                     (let ((a!13 (ite a!9
                                      (_tuple_1 (_tuple_0 0 INF) 0)
                                      (_tuple_1 (_tuple_0 a!12 MSEC)
                                                (__f2 (__f2 a!4))))))
                       (and (= (__f1 a!4) B1) (= (__f2 a!8) a!13)))))))))
                     :skolemid _skolem_11
                     :qid _exists_3))))
     (let ((a!2 (ite (= i 6)
                     (__f7 initial_2_trace_C)
                     (ite (= i 7)
                          (__f8 initial_2_trace_C)
                          (ite (= i 8) (__f9 initial_2_trace_C) a!1)))))
     (let ((a!3 (ite (= i 3)
                     (__f4 initial_2_trace_C)
                     (ite (= i 4)
                          (__f5 initial_2_trace_C)
                          (ite (= i 5) (__f6 initial_2_trace_C) a!2)))))
     (let ((a!4 (ite (= i 0)
                     (__f1 initial_2_trace_C)
                     (ite (= i 1)
                          (__f2 initial_2_trace_C)
                          (ite (= i 2) (__f3 initial_2_trace_C) a!3)))))
     (let ((a!5 (not (and (= (__f1 a!4) C1) (not (<= 10 i))))))
       (or a!5 a!6))))))
     :skolemid _skolem_12
     :qid _forall_8)))
(assert (forall ((i Int))
  (! (let ((a!1 (ite (= i 9)
                     (__f10 initial_3_trace_B)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0)))))
     (let ((a!2 (ite (= i 6)
                     (__f7 initial_3_trace_B)
                     (ite (= i 7)
                          (__f8 initial_3_trace_B)
                          (ite (= i 8) (__f9 initial_3_trace_B) a!1)))))
     (let ((a!3 (ite (= i 3)
                     (__f4 initial_3_trace_B)
                     (ite (= i 4)
                          (__f5 initial_3_trace_B)
                          (ite (= i 5) (__f6 initial_3_trace_B) a!2)))))
     (let ((a!4 (ite (= i 0)
                     (__f1 initial_3_trace_B)
                     (ite (= i 1)
                          (__f2 initial_3_trace_B)
                          (ite (= i 2) (__f3 initial_3_trace_B) a!3)))))
     (let ((a!5 (>= (__f1 (__f1 (__f2 a!4))) 0)))
     (let ((a!6 (and a!5 (>= (__f2 (__f2 a!4)) 0))))
       (or (not (and (>= i 0) (<= i 9))) a!6)))))))
     :skolemid _skolem_13
     :qid _forall_9)))
(assert (forall ((i Int))
  (! (let ((a!1 (ite (= i 9)
                     (__f10 initial_1_trace_A)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0)))))
     (let ((a!2 (ite (= i 6)
                     (__f7 initial_1_trace_A)
                     (ite (= i 7)
                          (__f8 initial_1_trace_A)
                          (ite (= i 8) (__f9 initial_1_trace_A) a!1)))))
     (let ((a!3 (ite (= i 3)
                     (__f4 initial_1_trace_A)
                     (ite (= i 4)
                          (__f5 initial_1_trace_A)
                          (ite (= i 5) (__f6 initial_1_trace_A) a!2)))))
     (let ((a!4 (ite (= i 0)
                     (__f1 initial_1_trace_A)
                     (ite (= i 1)
                          (__f2 initial_1_trace_A)
                          (ite (= i 2) (__f3 initial_1_trace_A) a!3)))))
       (or (not (and (>= i 0) (<= i 9)))
           (= (__f1 a!4) A2)
           (= (__f1 a!4) NULL)
           (= (__f1 a!4) A1))))))
     :skolemid _skolem_14
     :qid _forall_10)))
(assert (forall ((i Int))
  (! (let ((a!1 (ite (= i 9)
                     (__f10 initial_3_trace_B)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0))))
           (a!6 (exists ((k Int))
                  (! (let ((a!1 (ite (= k 9)
                                     (__f10 initial_3_trace_B)
                                     (_tuple_2 NULL
                                               (_tuple_1 (_tuple_0 0 INF) 0))))
                           (a!5 (ite (= i 9)
                                     (__f10 initial_3_trace_B)
                                     (_tuple_2 NULL
                                               (_tuple_1 (_tuple_0 0 INF) 0)))))
                     (let ((a!2 (ite (= k 6)
                                     (__f7 initial_3_trace_B)
                                     (ite (= k 7)
                                          (__f8 initial_3_trace_B)
                                          (ite (= k 8)
                                               (__f9 initial_3_trace_B)
                                               a!1))))
                           (a!6 (ite (= i 6)
                                     (__f7 initial_3_trace_B)
                                     (ite (= i 7)
                                          (__f8 initial_3_trace_B)
                                          (ite (= i 8)
                                               (__f9 initial_3_trace_B)
                                               a!5)))))
                     (let ((a!3 (ite (= k 3)
                                     (__f4 initial_3_trace_B)
                                     (ite (= k 4)
                                          (__f5 initial_3_trace_B)
                                          (ite (= k 5)
                                               (__f6 initial_3_trace_B)
                                               a!2))))
                           (a!7 (ite (= i 3)
                                     (__f4 initial_3_trace_B)
                                     (ite (= i 4)
                                          (__f5 initial_3_trace_B)
                                          (ite (= i 5)
                                               (__f6 initial_3_trace_B)
                                               a!6)))))
                     (let ((a!4 (ite (= k 0)
                                     (__f1 initial_3_trace_B)
                                     (ite (= k 1)
                                          (__f2 initial_3_trace_B)
                                          (ite (= k 2)
                                               (__f3 initial_3_trace_B)
                                               a!3))))
                           (a!8 (ite (= i 0)
                                     (__f1 initial_3_trace_B)
                                     (ite (= i 1)
                                          (__f2 initial_3_trace_B)
                                          (ite (= i 2)
                                               (__f3 initial_3_trace_B)
                                               a!7)))))
                     (let ((a!9 (= (__f2 (__f1 (__f2 a!4))) INF))
                           (a!10 (= (__f2 (__f1 (__f2 a!4))) SEC))
                           (a!11 (* 1000 (__f1 (__f1 (__f2 a!4))))))
                     (let ((a!12 (__f1 (ite a!10
                                            (_tuple_0 a!11 MSEC)
                                            (__f1 (__f2 a!4))))))
                     (let ((a!13 (ite a!9
                                      (_tuple_1 (_tuple_0 0 INF) 0)
                                      (_tuple_1 (_tuple_0 (+ 1000 a!12) MSEC)
                                                (__f2 (__f2 a!4))))))
                       (and (= (__f1 a!4) B1)
                            (not (<= 9 k))
                            (= (__f2 a!8) a!13)))))))))
                     :skolemid _skolem_16
                     :qid _exists_5)))
           (a!7 (exists ((j Int))
                  (! (let ((a!1 (ite (= j 9)
                                     (__f10 initial_1_trace_A)
                                     (_tuple_2 NULL
                                               (_tuple_1 (_tuple_0 0 INF) 0))))
                           (a!5 (ite (= i 9)
                                     (__f10 initial_3_trace_B)
                                     (_tuple_2 NULL
                                               (_tuple_1 (_tuple_0 0 INF) 0)))))
                     (let ((a!2 (ite (= j 6)
                                     (__f7 initial_1_trace_A)
                                     (ite (= j 7)
                                          (__f8 initial_1_trace_A)
                                          (ite (= j 8)
                                               (__f9 initial_1_trace_A)
                                               a!1))))
                           (a!6 (ite (= i 6)
                                     (__f7 initial_3_trace_B)
                                     (ite (= i 7)
                                          (__f8 initial_3_trace_B)
                                          (ite (= i 8)
                                               (__f9 initial_3_trace_B)
                                               a!5)))))
                     (let ((a!3 (ite (= j 3)
                                     (__f4 initial_1_trace_A)
                                     (ite (= j 4)
                                          (__f5 initial_1_trace_A)
                                          (ite (= j 5)
                                               (__f6 initial_1_trace_A)
                                               a!2))))
                           (a!7 (ite (= i 3)
                                     (__f4 initial_3_trace_B)
                                     (ite (= i 4)
                                          (__f5 initial_3_trace_B)
                                          (ite (= i 5)
                                               (__f6 initial_3_trace_B)
                                               a!6)))))
                     (let ((a!4 (ite (= j 0)
                                     (__f1 initial_1_trace_A)
                                     (ite (= j 1)
                                          (__f2 initial_1_trace_A)
                                          (ite (= j 2)
                                               (__f3 initial_1_trace_A)
                                               a!3))))
                           (a!8 (ite (= i 0)
                                     (__f1 initial_3_trace_B)
                                     (ite (= i 1)
                                          (__f2 initial_3_trace_B)
                                          (ite (= i 2)
                                               (__f3 initial_3_trace_B)
                                               a!7)))))
                     (let ((a!9 (= (__f2 (__f1 (__f2 a!4))) INF))
                           (a!10 (= (__f2 (__f1 (__f2 a!4))) SEC))
                           (a!11 (* 1000 (__f1 (__f1 (__f2 a!4))))))
                     (let ((a!12 (__f1 (ite a!10
                                            (_tuple_0 a!11 MSEC)
                                            (__f1 (__f2 a!4))))))
                     (let ((a!13 (ite a!9
                                      (_tuple_1 (_tuple_0 0 INF) 0)
                                      (_tuple_1 (_tuple_0 a!12 MSEC)
                                                (__f2 (__f2 a!4))))))
                       (and (= (__f1 a!4) A2)
                            (not (<= 9 j))
                            (= (__f2 a!8) a!13)))))))))
                     :skolemid _skolem_15
                     :qid _exists_4))))
     (let ((a!2 (ite (= i 6)
                     (__f7 initial_3_trace_B)
                     (ite (= i 7)
                          (__f8 initial_3_trace_B)
                          (ite (= i 8) (__f9 initial_3_trace_B) a!1)))))
     (let ((a!3 (ite (= i 3)
                     (__f4 initial_3_trace_B)
                     (ite (= i 4)
                          (__f5 initial_3_trace_B)
                          (ite (= i 5) (__f6 initial_3_trace_B) a!2)))))
     (let ((a!4 (ite (= i 0)
                     (__f1 initial_3_trace_B)
                     (ite (= i 1)
                          (__f2 initial_3_trace_B)
                          (ite (= i 2) (__f3 initial_3_trace_B) a!3)))))
     (let ((a!5 (not (and (= (__f1 a!4) B1) (not (<= 10 i))))))
       (or a!5 a!6 a!7))))))
     :skolemid _skolem_17
     :qid _forall_11)))
(assert (forall ((i Int) (j Int))
  (! (let ((a!1 (ite (= i 9)
                     (__f10 initial_1_trace_A)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0))))
           (a!5 (ite (= j 9)
                     (__f10 initial_1_trace_A)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0)))))
     (let ((a!2 (ite (= i 6)
                     (__f7 initial_1_trace_A)
                     (ite (= i 7)
                          (__f8 initial_1_trace_A)
                          (ite (= i 8) (__f9 initial_1_trace_A) a!1))))
           (a!6 (ite (= j 6)
                     (__f7 initial_1_trace_A)
                     (ite (= j 7)
                          (__f8 initial_1_trace_A)
                          (ite (= j 8) (__f9 initial_1_trace_A) a!5)))))
     (let ((a!3 (ite (= i 3)
                     (__f4 initial_1_trace_A)
                     (ite (= i 4)
                          (__f5 initial_1_trace_A)
                          (ite (= i 5) (__f6 initial_1_trace_A) a!2))))
           (a!7 (ite (= j 3)
                     (__f4 initial_1_trace_A)
                     (ite (= j 4)
                          (__f5 initial_1_trace_A)
                          (ite (= j 5) (__f6 initial_1_trace_A) a!6)))))
     (let ((a!4 (ite (= i 0)
                     (__f1 initial_1_trace_A)
                     (ite (= i 1)
                          (__f2 initial_1_trace_A)
                          (ite (= i 2) (__f3 initial_1_trace_A) a!3))))
           (a!8 (ite (= j 0)
                     (__f1 initial_1_trace_A)
                     (ite (= j 1)
                          (__f2 initial_1_trace_A)
                          (ite (= j 2) (__f3 initial_1_trace_A) a!7)))))
       (or (not (and (>= i 0) (<= i 9) (>= j 0) (<= j 9)))
           (= i j)
           (not (= (__f1 a!4) (__f1 a!8)))
           (not (= (__f2 a!4) (__f2 a!8))))))))
     :skolemid _skolem_18
     :qid _forall_12)))
(assert (forall ((i Int) (j Int))
  (! (let ((a!1 (not (and (not (<= j i)) (>= i 0) (<= i 9) (>= j 0) (<= j 9))))
           (a!2 (ite (= i 9)
                     (__f10 initial_3_trace_B)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0))))
           (a!7 (ite (= j 9)
                     (__f10 initial_3_trace_B)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0)))))
     (let ((a!3 (ite (= i 6)
                     (__f7 initial_3_trace_B)
                     (ite (= i 7)
                          (__f8 initial_3_trace_B)
                          (ite (= i 8) (__f9 initial_3_trace_B) a!2))))
           (a!8 (ite (= j 6)
                     (__f7 initial_3_trace_B)
                     (ite (= j 7)
                          (__f8 initial_3_trace_B)
                          (ite (= j 8) (__f9 initial_3_trace_B) a!7)))))
     (let ((a!4 (ite (= i 3)
                     (__f4 initial_3_trace_B)
                     (ite (= i 4)
                          (__f5 initial_3_trace_B)
                          (ite (= i 5) (__f6 initial_3_trace_B) a!3))))
           (a!9 (ite (= j 3)
                     (__f4 initial_3_trace_B)
                     (ite (= j 4)
                          (__f5 initial_3_trace_B)
                          (ite (= j 5) (__f6 initial_3_trace_B) a!8)))))
     (let ((a!5 (ite (= i 0)
                     (__f1 initial_3_trace_B)
                     (ite (= i 1)
                          (__f2 initial_3_trace_B)
                          (ite (= i 2) (__f3 initial_3_trace_B) a!4))))
           (a!10 (ite (= j 0)
                      (__f1 initial_3_trace_B)
                      (ite (= j 1)
                           (__f2 initial_3_trace_B)
                           (ite (= j 2) (__f3 initial_3_trace_B) a!9)))))
     (let ((a!6 (= (__f2 (__f1 (__f2 a!5))) INF))
           (a!11 (= (__f2 (__f1 (__f2 a!10))) INF))
           (a!12 (= (__f2 (__f1 (__f2 a!5))) SEC))
           (a!13 (* 1000 (__f1 (__f1 (__f2 a!5)))))
           (a!14 (= (__f2 (__f1 (__f2 a!10))) SEC))
           (a!15 (* 1000 (__f1 (__f1 (__f2 a!10)))))
           (a!20 (not (<= (__f2 (__f2 a!5)) (__f2 (__f2 a!10))))))
     (let ((a!16 (= (ite a!12 (_tuple_0 a!13 MSEC) (__f1 (__f2 a!5)))
                    (ite a!14 (_tuple_0 a!15 MSEC) (__f1 (__f2 a!10)))))
           (a!18 (__f1 (ite a!12 (_tuple_0 a!13 MSEC) (__f1 (__f2 a!5)))))
           (a!19 (__f1 (ite a!14 (_tuple_0 a!15 MSEC) (__f1 (__f2 a!10))))))
     (let ((a!17 (and a!16 (= (__f2 (__f2 a!5)) (__f2 (__f2 a!10)))))
           (a!21 (not (or (and (not a!6) a!11)
                          (and (= a!18 a!19) a!20)
                          (not (<= a!18 a!19))))))
     (let ((a!22 (and a!21 (not (or (and a!6 a!11) a!17)))))
       (or a!1 (and a!6 a!11) a!17 a!22)))))))))
     :skolemid _skolem_19
     :qid _forall_13)))
(assert (forall ((j Int))
  (! (let ((a!1 (ite (= j 9)
                     (__f10 initial_3_trace_B)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0)))))
     (let ((a!2 (ite (= j 6)
                     (__f7 initial_3_trace_B)
                     (ite (= j 7)
                          (__f8 initial_3_trace_B)
                          (ite (= j 8) (__f9 initial_3_trace_B) a!1)))))
     (let ((a!3 (ite (= j 3)
                     (__f4 initial_3_trace_B)
                     (ite (= j 4)
                          (__f5 initial_3_trace_B)
                          (ite (= j 5) (__f6 initial_3_trace_B) a!2)))))
     (let ((a!4 (ite (= j 0)
                     (__f1 initial_3_trace_B)
                     (ite (= j 1)
                          (__f2 initial_3_trace_B)
                          (ite (= j 2) (__f3 initial_3_trace_B) a!3)))))
       (or (not (and (>= j 0) (<= j 9))) (= (__f1 a!4) B1) (= (__f1 a!4) NULL))))))
     :skolemid _skolem_20
     :qid _forall_14)))
(assert (forall ((i Int))
  (! (let ((a!1 (ite (= i 9)
                     (__f10 initial_3_trace_B)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0))))
           (a!6 (exists ((j Int))
                  (! (let ((a!1 (ite (= j 9)
                                     (__f10 initial_3_trace_B)
                                     (_tuple_2 NULL
                                               (_tuple_1 (_tuple_0 0 INF) 0))))
                           (a!5 (ite (= i 9)
                                     (__f10 initial_3_trace_B)
                                     (_tuple_2 NULL
                                               (_tuple_1 (_tuple_0 0 INF) 0)))))
                     (let ((a!2 (ite (= j 6)
                                     (__f7 initial_3_trace_B)
                                     (ite (= j 7)
                                          (__f8 initial_3_trace_B)
                                          (ite (= j 8)
                                               (__f9 initial_3_trace_B)
                                               a!1))))
                           (a!6 (ite (= i 6)
                                     (__f7 initial_3_trace_B)
                                     (ite (= i 7)
                                          (__f8 initial_3_trace_B)
                                          (ite (= i 8)
                                               (__f9 initial_3_trace_B)
                                               a!5)))))
                     (let ((a!3 (ite (= j 3)
                                     (__f4 initial_3_trace_B)
                                     (ite (= j 4)
                                          (__f5 initial_3_trace_B)
                                          (ite (= j 5)
                                               (__f6 initial_3_trace_B)
                                               a!2))))
                           (a!7 (ite (= i 3)
                                     (__f4 initial_3_trace_B)
                                     (ite (= i 4)
                                          (__f5 initial_3_trace_B)
                                          (ite (= i 5)
                                               (__f6 initial_3_trace_B)
                                               a!6)))))
                     (let ((a!4 (ite (= j 0)
                                     (__f1 initial_3_trace_B)
                                     (ite (= j 1)
                                          (__f2 initial_3_trace_B)
                                          (ite (= j 2)
                                               (__f3 initial_3_trace_B)
                                               a!3))))
                           (a!8 (ite (= i 0)
                                     (__f1 initial_3_trace_B)
                                     (ite (= i 1)
                                          (__f2 initial_3_trace_B)
                                          (ite (= i 2)
                                               (__f3 initial_3_trace_B)
                                               a!7)))))
                     (let ((a!9 (= (__f2 (__f1 (__f2 a!8))) INF))
                           (a!10 (= (__f2 (__f1 (__f2 a!8))) SEC))
                           (a!11 (* 1000 (__f1 (__f1 (__f2 a!8))))))
                     (let ((a!12 (__f1 (ite a!10
                                            (_tuple_0 a!11 MSEC)
                                            (__f1 (__f2 a!8))))))
                     (let ((a!13 (ite a!9
                                      (_tuple_1 (_tuple_0 0 INF) 0)
                                      (_tuple_1 (_tuple_0 (+ 1000 a!12) MSEC)
                                                (__f2 (__f2 a!8))))))
                       (and (= (__f1 a!4) B1) (= (__f2 a!4) a!13)))))))))
                     :skolemid _skolem_21
                     :qid _exists_6))))
     (let ((a!2 (ite (= i 6)
                     (__f7 initial_3_trace_B)
                     (ite (= i 7)
                          (__f8 initial_3_trace_B)
                          (ite (= i 8) (__f9 initial_3_trace_B) a!1)))))
     (let ((a!3 (ite (= i 3)
                     (__f4 initial_3_trace_B)
                     (ite (= i 4)
                          (__f5 initial_3_trace_B)
                          (ite (= i 5) (__f6 initial_3_trace_B) a!2)))))
     (let ((a!4 (ite (= i 0)
                     (__f1 initial_3_trace_B)
                     (ite (= i 1)
                          (__f2 initial_3_trace_B)
                          (ite (= i 2) (__f3 initial_3_trace_B) a!3)))))
     (let ((a!5 (not (and (= (__f1 a!4) B1) (not (<= 9 i))))))
       (or a!5 a!6))))))
     :skolemid _skolem_22
     :qid _forall_15)))
(assert (forall ((i Int) (j Int))
  (! (let ((a!1 (not (and (not (<= j i)) (>= i 0) (<= i 9) (>= j 0) (<= j 9))))
           (a!2 (ite (= i 9)
                     (__f10 initial_1_trace_A)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0))))
           (a!7 (ite (= j 9)
                     (__f10 initial_1_trace_A)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0)))))
     (let ((a!3 (ite (= i 6)
                     (__f7 initial_1_trace_A)
                     (ite (= i 7)
                          (__f8 initial_1_trace_A)
                          (ite (= i 8) (__f9 initial_1_trace_A) a!2))))
           (a!8 (ite (= j 6)
                     (__f7 initial_1_trace_A)
                     (ite (= j 7)
                          (__f8 initial_1_trace_A)
                          (ite (= j 8) (__f9 initial_1_trace_A) a!7)))))
     (let ((a!4 (ite (= i 3)
                     (__f4 initial_1_trace_A)
                     (ite (= i 4)
                          (__f5 initial_1_trace_A)
                          (ite (= i 5) (__f6 initial_1_trace_A) a!3))))
           (a!9 (ite (= j 3)
                     (__f4 initial_1_trace_A)
                     (ite (= j 4)
                          (__f5 initial_1_trace_A)
                          (ite (= j 5) (__f6 initial_1_trace_A) a!8)))))
     (let ((a!5 (ite (= i 0)
                     (__f1 initial_1_trace_A)
                     (ite (= i 1)
                          (__f2 initial_1_trace_A)
                          (ite (= i 2) (__f3 initial_1_trace_A) a!4))))
           (a!10 (ite (= j 0)
                      (__f1 initial_1_trace_A)
                      (ite (= j 1)
                           (__f2 initial_1_trace_A)
                           (ite (= j 2) (__f3 initial_1_trace_A) a!9)))))
     (let ((a!6 (= (__f2 (__f1 (__f2 a!5))) INF))
           (a!11 (= (__f2 (__f1 (__f2 a!10))) INF))
           (a!12 (= (__f2 (__f1 (__f2 a!5))) SEC))
           (a!13 (* 1000 (__f1 (__f1 (__f2 a!5)))))
           (a!14 (= (__f2 (__f1 (__f2 a!10))) SEC))
           (a!15 (* 1000 (__f1 (__f1 (__f2 a!10)))))
           (a!20 (not (<= (__f2 (__f2 a!5)) (__f2 (__f2 a!10))))))
     (let ((a!16 (= (ite a!12 (_tuple_0 a!13 MSEC) (__f1 (__f2 a!5)))
                    (ite a!14 (_tuple_0 a!15 MSEC) (__f1 (__f2 a!10)))))
           (a!18 (__f1 (ite a!12 (_tuple_0 a!13 MSEC) (__f1 (__f2 a!5)))))
           (a!19 (__f1 (ite a!14 (_tuple_0 a!15 MSEC) (__f1 (__f2 a!10))))))
     (let ((a!17 (and a!16 (= (__f2 (__f2 a!5)) (__f2 (__f2 a!10)))))
           (a!21 (not (or (and (not a!6) a!11)
                          (and (= a!18 a!19) a!20)
                          (not (<= a!18 a!19))))))
     (let ((a!22 (and a!21 (not (or (and a!6 a!11) a!17)))))
       (or a!1 (and a!6 a!11) a!17 a!22)))))))))
     :skolemid _skolem_23
     :qid _forall_16)))
(assert (forall ((i Int))
  (! (let ((a!1 (ite (= i 9)
                     (__f10 initial_1_trace_A)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0))))
           (a!6 (exists ((j Int))
                  (! (let ((a!1 (ite (= j 9)
                                     (__f10 initial_1_trace_A)
                                     (_tuple_2 NULL
                                               (_tuple_1 (_tuple_0 0 INF) 0))))
                           (a!5 (ite (= i 9)
                                     (__f10 initial_1_trace_A)
                                     (_tuple_2 NULL
                                               (_tuple_1 (_tuple_0 0 INF) 0)))))
                     (let ((a!2 (ite (= j 6)
                                     (__f7 initial_1_trace_A)
                                     (ite (= j 7)
                                          (__f8 initial_1_trace_A)
                                          (ite (= j 8)
                                               (__f9 initial_1_trace_A)
                                               a!1))))
                           (a!6 (ite (= i 6)
                                     (__f7 initial_1_trace_A)
                                     (ite (= i 7)
                                          (__f8 initial_1_trace_A)
                                          (ite (= i 8)
                                               (__f9 initial_1_trace_A)
                                               a!5)))))
                     (let ((a!3 (ite (= j 3)
                                     (__f4 initial_1_trace_A)
                                     (ite (= j 4)
                                          (__f5 initial_1_trace_A)
                                          (ite (= j 5)
                                               (__f6 initial_1_trace_A)
                                               a!2))))
                           (a!7 (ite (= i 3)
                                     (__f4 initial_1_trace_A)
                                     (ite (= i 4)
                                          (__f5 initial_1_trace_A)
                                          (ite (= i 5)
                                               (__f6 initial_1_trace_A)
                                               a!6)))))
                     (let ((a!4 (ite (= j 0)
                                     (__f1 initial_1_trace_A)
                                     (ite (= j 1)
                                          (__f2 initial_1_trace_A)
                                          (ite (= j 2)
                                               (__f3 initial_1_trace_A)
                                               a!3))))
                           (a!8 (ite (= i 0)
                                     (__f1 initial_1_trace_A)
                                     (ite (= i 1)
                                          (__f2 initial_1_trace_A)
                                          (ite (= i 2)
                                               (__f3 initial_1_trace_A)
                                               a!7)))))
                     (let ((a!9 (= (__f2 (__f1 (__f2 a!8))) INF))
                           (a!10 (= (__f2 (__f1 (__f2 a!8))) SEC))
                           (a!11 (* 1000 (__f1 (__f1 (__f2 a!8))))))
                     (let ((a!12 (__f1 (ite a!10
                                            (_tuple_0 a!11 MSEC)
                                            (__f1 (__f2 a!8))))))
                     (let ((a!13 (ite a!9
                                      (_tuple_1 (_tuple_0 0 INF) 0)
                                      (_tuple_1 (_tuple_0 (+ 5000 a!12) MSEC)
                                                (__f2 (__f2 a!8))))))
                       (and (= (__f1 a!4) A1) (= (__f2 a!4) a!13)))))))))
                     :skolemid _skolem_24
                     :qid _exists_7))))
     (let ((a!2 (ite (= i 6)
                     (__f7 initial_1_trace_A)
                     (ite (= i 7)
                          (__f8 initial_1_trace_A)
                          (ite (= i 8) (__f9 initial_1_trace_A) a!1)))))
     (let ((a!3 (ite (= i 3)
                     (__f4 initial_1_trace_A)
                     (ite (= i 4)
                          (__f5 initial_1_trace_A)
                          (ite (= i 5) (__f6 initial_1_trace_A) a!2)))))
     (let ((a!4 (ite (= i 0)
                     (__f1 initial_1_trace_A)
                     (ite (= i 1)
                          (__f2 initial_1_trace_A)
                          (ite (= i 2) (__f3 initial_1_trace_A) a!3)))))
     (let ((a!5 (not (and (= (__f1 a!4) A1) (not (<= 9 i))))))
       (or a!5 a!6))))))
     :skolemid _skolem_25
     :qid _forall_17)))
(assert (forall ((i Int) (j Int))
  (! (let ((a!1 (ite (= i 9)
                     (__f10 initial_3_trace_B)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0))))
           (a!5 (ite (= j 9)
                     (__f10 initial_3_trace_B)
                     (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0)))))
     (let ((a!2 (ite (= i 6)
                     (__f7 initial_3_trace_B)
                     (ite (= i 7)
                          (__f8 initial_3_trace_B)
                          (ite (= i 8) (__f9 initial_3_trace_B) a!1))))
           (a!6 (ite (= j 6)
                     (__f7 initial_3_trace_B)
                     (ite (= j 7)
                          (__f8 initial_3_trace_B)
                          (ite (= j 8) (__f9 initial_3_trace_B) a!5)))))
     (let ((a!3 (ite (= i 3)
                     (__f4 initial_3_trace_B)
                     (ite (= i 4)
                          (__f5 initial_3_trace_B)
                          (ite (= i 5) (__f6 initial_3_trace_B) a!2))))
           (a!7 (ite (= j 3)
                     (__f4 initial_3_trace_B)
                     (ite (= j 4)
                          (__f5 initial_3_trace_B)
                          (ite (= j 5) (__f6 initial_3_trace_B) a!6)))))
     (let ((a!4 (ite (= i 0)
                     (__f1 initial_3_trace_B)
                     (ite (= i 1)
                          (__f2 initial_3_trace_B)
                          (ite (= i 2) (__f3 initial_3_trace_B) a!3))))
           (a!8 (ite (= j 0)
                     (__f1 initial_3_trace_B)
                     (ite (= j 1)
                          (__f2 initial_3_trace_B)
                          (ite (= j 2) (__f3 initial_3_trace_B) a!7)))))
       (or (not (and (>= i 0) (<= i 9) (>= j 0) (<= j 9)))
           (= i j)
           (not (= (__f1 a!4) (__f1 a!8)))
           (not (= (__f2 a!4) (__f2 a!8))))))))
     :skolemid _skolem_26
     :qid _forall_18)))
(assert (not (forall ((i Int))
       (! (let ((a!1 (ite (= i 9)
                          (__f10 initial_1_trace_A)
                          (_tuple_2 NULL (_tuple_1 (_tuple_0 0 INF) 0))))
                (a!7 (exists ((j Int))
                       (! (let ((a!1 (__f2 (__f1 (__f2 (__f10 initial_2_trace_C)))))
                                (a!2 (ite (= j 9)
                                          (__f10 initial_2_trace_C)
                                          (_tuple_2 NULL
                                                    (_tuple_1 (_tuple_0 0 INF)
                                                              0))))
                                (a!7 (__f1 (__f1 (__f2 (__f10 initial_2_trace_C)))))
                                (a!17 (ite (= i 9)
                                           (__f10 initial_1_trace_A)
                                           (_tuple_2 NULL
                                                     (_tuple_1 (_tuple_0 0 INF)
                                                               0)))))
                          (let ((a!3 (ite (= j 6)
                                          (__f7 initial_2_trace_C)
                                          (ite (= j 7)
                                               (__f8 initial_2_trace_C)
                                               (ite (= j 8)
                                                    (__f9 initial_2_trace_C)
                                                    a!2))))
                                (a!8 (ite (= a!1 SEC)
                                          (_tuple_0 (* 1000 a!7) MSEC)
                                          (__f1 (__f2 (__f10 initial_2_trace_C)))))
                                (a!18 (ite (= i 6)
                                           (__f7 initial_1_trace_A)
                                           (ite (= i 7)
                                                (__f8 initial_1_trace_A)
                                                (ite (= i 8)
                                                     (__f9 initial_1_trace_A)
                                                     a!17)))))
                          (let ((a!4 (ite (= j 3)
                                          (__f4 initial_2_trace_C)
                                          (ite (= j 4)
                                               (__f5 initial_2_trace_C)
                                               (ite (= j 5)
                                                    (__f6 initial_2_trace_C)
                                                    a!3))))
                                (a!19 (ite (= i 3)
                                           (__f4 initial_1_trace_A)
                                           (ite (= i 4)
                                                (__f5 initial_1_trace_A)
                                                (ite (= i 5)
                                                     (__f6 initial_1_trace_A)
                                                     a!18)))))
                          (let ((a!5 (ite (= j 0)
                                          (__f1 initial_2_trace_C)
                                          (ite (= j 1)
                                               (__f2 initial_2_trace_C)
                                               (ite (= j 2)
                                                    (__f3 initial_2_trace_C)
                                                    a!4))))
                                (a!20 (ite (= i 0)
                                           (__f1 initial_1_trace_A)
                                           (ite (= i 1)
                                                (__f2 initial_1_trace_A)
                                                (ite (= i 2)
                                                     (__f3 initial_1_trace_A)
                                                     a!19)))))
                          (let ((a!6 (= (__f2 (__f1 (__f2 a!5))) INF))
                                (a!9 (= (__f2 (__f1 (__f2 a!5))) SEC))
                                (a!10 (* 1000 (__f1 (__f1 (__f2 a!5)))))
                                (a!12 (<= (__f2 (__f2 (__f10 initial_2_trace_C)))
                                          (__f2 (__f2 a!5))))
                                (a!15 (= (__f2 (__f2 (__f10 initial_2_trace_C)))
                                         (__f2 (__f2 a!5))))
                                (a!21 (= (__f2 (__f1 (__f2 a!20))) INF))
                                (a!22 (ite (and (= (__f1 a!20) A2)
                                                (= (__f1 a!5) C1))
                                           (_tuple_1 (_tuple_0 0 MSEC) 0)
                                           (_tuple_1 (_tuple_0 0 INF) 0)))
                                (a!28 (ite (and (= (__f1 a!20) A1)
                                                (= (__f1 a!5) C1))
                                           (_tuple_1 (_tuple_0 0 MSEC) 0)
                                           (_tuple_1 (_tuple_0 0 INF) 0)))
                                (a!34 (= (__f2 (__f1 (__f2 a!20))) SEC))
                                (a!35 (* 1000 (__f1 (__f1 (__f2 a!20))))))
                          (let ((a!11 (__f1 (ite a!9
                                                 (_tuple_0 a!10 MSEC)
                                                 (__f1 (__f2 a!5)))))
                                (a!14 (= a!8
                                         (ite a!9
                                              (_tuple_0 a!10 MSEC)
                                              (__f1 (__f2 a!5)))))
                                (a!23 (ite (and (= (__f1 a!20) B1)
                                                (= (__f1 a!5) C1))
                                           (_tuple_1 (_tuple_0 0 MSEC) 0)
                                           a!22))
                                (a!29 (ite (and (= (__f1 a!20) A1)
                                                (= (__f1 a!5) B1))
                                           (_tuple_1 (_tuple_0 0 MSEC) 0)
                                           a!28))
                                (a!36 (__f1 (ite a!34
                                                 (_tuple_0 a!35 MSEC)
                                                 (__f1 (__f2 a!20))))))
                          (let ((a!13 (or (and (not (= a!1 INF)) a!6)
                                          (and (= (__f1 a!8) a!11) (not a!12))
                                          (not (<= (__f1 a!8) a!11))))
                                (a!16 (not (or (and (= a!1 INF) a!6)
                                               (and a!14 a!15))))
                                (a!24 (ite (and (= (__f1 a!20) B1)
                                                (= (__f1 a!5) B1))
                                           (_tuple_1 (_tuple_0 1 SEC) 0)
                                           a!23))
                                (a!30 (ite (and (= (__f1 a!20) A2)
                                                (= (__f1 a!5) A1))
                                           (_tuple_1 (_tuple_0 0 MSEC) 1)
                                           a!29)))
                          (let ((a!25 (ite (and (= (__f1 a!20) A2)
                                                (= (__f1 a!5) B1))
                                           (_tuple_1 (_tuple_0 0 MSEC) 0)
                                           a!24))
                                (a!31 (ite (and (= (__f1 a!20) A1)
                                                (= (__f1 a!5) A2))
                                           (_tuple_1 (_tuple_0 0 MSEC) 0)
                                           a!30)))
                          (let ((a!26 (ite (and (= (__f1 a!20) A2)
                                                (= (__f1 a!5) A2))
                                           (_tuple_1 (_tuple_0 5 SEC) 0)
                                           a!25)))
                          (let ((a!27 (ite (and (= (__f1 a!20) A1)
                                                (= (__f1 a!5) A1))
                                           (_tuple_1 (_tuple_0 5 SEC) 0)
                                           a!26)))
                          (let ((a!32 (ite (= a!27
                                              (_tuple_1 (_tuple_0 0 INF) 0))
                                           a!31
                                           a!27)))
                          (let ((a!33 (not (= (__f2 (__f1 a!32)) INF)))
                                (a!37 (_tuple_0 (* 1000 (__f1 (__f1 a!32)))
                                                MSEC)))
                          (let ((a!38 (ite (= (__f2 (__f1 a!32)) SEC)
                                           a!37
                                           (__f1 a!32))))
                          (let ((a!39 (_tuple_1 (_tuple_0 (+ a!36 (__f1 a!38))
                                                          MSEC)
                                                (+ (__f2 (__f2 a!20))
                                                   (__f2 a!32)))))
                          (let ((a!40 (ite (and (not a!21) a!33)
                                           a!39
                                           (_tuple_1 (_tuple_0 0 INF) 0))))
                          (let ((a!41 (_tuple_0 (* 1000 (__f1 (__f1 a!40)))
                                                MSEC))
                                (a!43 (not (<= (__f2 a!40) (__f2 (__f2 a!5)))))
                                (a!44 (not (= (__f2 (__f1 a!40)) INF))))
                          (let ((a!42 (ite (= (__f2 (__f1 a!40)) SEC)
                                           a!41
                                           (__f1 a!40))))
                          (let ((a!45 (or (not (<= (__f1 a!42) a!11))
                                          (and (= (__f1 a!42) a!11) a!43)
                                          (and a!44 a!6))))
                            (or (and (not a!13) a!16)
                                (and (= (__f1 a!5) C1) (not a!45)))))))))))))))))))))
                          :skolemid _skolem_27
                          :qid _exists_8))))
          (let ((a!2 (ite (= i 6)
                          (__f7 initial_1_trace_A)
                          (ite (= i 7)
                               (__f8 initial_1_trace_A)
                               (ite (= i 8) (__f9 initial_1_trace_A) a!1)))))
          (let ((a!3 (ite (= i 3)
                          (__f4 initial_1_trace_A)
                          (ite (= i 4)
                               (__f5 initial_1_trace_A)
                               (ite (= i 5) (__f6 initial_1_trace_A) a!2)))))
          (let ((a!4 (ite (= i 0)
                          (__f1 initial_1_trace_A)
                          (ite (= i 1)
                               (__f2 initial_1_trace_A)
                               (ite (= i 2) (__f3 initial_1_trace_A) a!3)))))
          (let ((a!5 (= (__f2 (__f1 (__f2 a!4))) INF)))
          (let ((a!6 (not (and (= i 0) (= (__f1 a!4) A1) (not a!5)))))
            (or a!6 a!7)))))))
          :skolemid _skolem_28
          :qid _forall_19))))


(check-sat)
(get-info :all-statistics)
(get-model)
