(declare-datatypes ((_enum_0 0)) (((INF) (SEC) (MSEC))))
(declare-datatypes ((_tuple_0 0)) (((_tuple_0 (__f1 Int) (__f2 _enum_0)))))
(declare-datatypes ((_tuple_1 0)) (((_tuple_1 (__f1 _tuple_0) (__f2 Int)))))
(declare-datatypes ((_enum_1 0)) (((NULL) (A1) (B1) (C1) (STARTUP) (A_out) (B_in) (B_out) (C_in) (B_ramp_exists) (C_s))))
(declare-datatypes ((_tuple_2 0)) (((_tuple_2 (__f1 _enum_1) (__f2 Bool) (__f3 _tuple_1)))))
(declare-datatypes ((_tuple_3 0)) (((_tuple_3 (__f1 _tuple_2) (__f2 _tuple_2) (__f3 _tuple_2) (__f4 _tuple_2) (__f5 _tuple_2) (__f6 _tuple_2) (__f7 _tuple_2) (__f8 _tuple_2) (__f9 _tuple_2) (__f10 _tuple_2)))))
(declare-fun initial_1_trace () _tuple_3)
(assert (forall ((i Int) (j Int))
  (! (let ((a!1 (not (and (not (<= j i)) (>= i 0) (<= i 9) (>= j 0) (<= j 9))))
           (a!2 (ite (= i 9)
                     (__f10 initial_1_trace)
                     (_tuple_2 NULL false (_tuple_1 (_tuple_0 0 INF) 0))))
           (a!8 (ite (= j 9)
                     (__f10 initial_1_trace)
                     (_tuple_2 NULL false (_tuple_1 (_tuple_0 0 INF) 0)))))
     (let ((a!3 (ite (= i 6)
                     (__f7 initial_1_trace)
                     (ite (= i 7)
                          (__f8 initial_1_trace)
                          (ite (= i 8) (__f9 initial_1_trace) a!2))))
           (a!9 (ite (= j 6)
                     (__f7 initial_1_trace)
                     (ite (= j 7)
                          (__f8 initial_1_trace)
                          (ite (= j 8) (__f9 initial_1_trace) a!8)))))
     (let ((a!4 (ite (= i 3)
                     (__f4 initial_1_trace)
                     (ite (= i 4)
                          (__f5 initial_1_trace)
                          (ite (= i 5) (__f6 initial_1_trace) a!3))))
           (a!10 (ite (= j 3)
                      (__f4 initial_1_trace)
                      (ite (= j 4)
                           (__f5 initial_1_trace)
                           (ite (= j 5) (__f6 initial_1_trace) a!9)))))
     (let ((a!5 (ite (= i 0)
                     (__f1 initial_1_trace)
                     (ite (= i 1)
                          (__f2 initial_1_trace)
                          (ite (= i 2) (__f3 initial_1_trace) a!4))))
           (a!11 (ite (= j 0)
                      (__f1 initial_1_trace)
                      (ite (= j 1)
                           (__f2 initial_1_trace)
                           (ite (= j 2) (__f3 initial_1_trace) a!10)))))
     (let ((a!6 (= (__f2 (__f1 (__f3 a!5))) SEC))
           (a!7 (* 1000 (__f1 (__f1 (__f3 a!5)))))
           (a!12 (= (__f2 (__f1 (__f3 a!11))) SEC))
           (a!13 (* 1000 (__f1 (__f1 (__f3 a!11)))))
           (a!16 (= (__f2 (__f1 (__f3 a!5))) INF))
           (a!17 (= (__f2 (__f1 (__f3 a!11))) INF))
           (a!20 (not (<= (__f2 (__f3 a!5)) (__f2 (__f3 a!11))))))
     (let ((a!14 (= (ite a!6 (_tuple_0 a!7 MSEC) (__f1 (__f3 a!5)))
                    (ite a!12 (_tuple_0 a!13 MSEC) (__f1 (__f3 a!11)))))
           (a!18 (__f1 (ite a!6 (_tuple_0 a!7 MSEC) (__f1 (__f3 a!5)))))
           (a!19 (__f1 (ite a!12 (_tuple_0 a!13 MSEC) (__f1 (__f3 a!11))))))
     (let ((a!15 (and a!14 (= (__f2 (__f3 a!5)) (__f2 (__f3 a!11)))))
           (a!21 (not (or (and (not a!16) a!17)
                          (and (= a!18 a!19) a!20)
                          (not (<= a!18 a!19))))))
       (or a!1 a!15 (and a!21 (not a!15))))))))))
     :skolemid _skolem_0
     :qid _forall_0)))
(assert (forall ((j Int))
  (! (let ((a!1 (ite (= j 9)
                     (__f10 initial_1_trace)
                     (_tuple_2 NULL false (_tuple_1 (_tuple_0 0 INF) 0))))
           (a!5 (forall ((i Int))
                  (! (let ((a!1 (ite (= i 9)
                                     (__f10 initial_1_trace)
                                     (_tuple_2 NULL
                                               false
                                               (_tuple_1 (_tuple_0 0 INF) 0)))))
                     (let ((a!2 (ite (= i 6)
                                     (__f7 initial_1_trace)
                                     (ite (= i 7)
                                          (__f8 initial_1_trace)
                                          (ite (= i 8)
                                               (__f9 initial_1_trace)
                                               a!1)))))
                     (let ((a!3 (ite (= i 3)
                                     (__f4 initial_1_trace)
                                     (ite (= i 4)
                                          (__f5 initial_1_trace)
                                          (ite (= i 5)
                                               (__f6 initial_1_trace)
                                               a!2)))))
                     (let ((a!4 (ite (= i 0)
                                     (__f1 initial_1_trace)
                                     (ite (= i 1)
                                          (__f2 initial_1_trace)
                                          (ite (= i 2)
                                               (__f3 initial_1_trace)
                                               a!3)))))
                       (or (not (and (>= i 0) (<= i 9)))
                           (not (= (__f1 a!4) NULL))
                           (<= j i))))))
                     :skolemid _skolem_1
                     :qid _forall_1))))
     (let ((a!2 (ite (= j 6)
                     (__f7 initial_1_trace)
                     (ite (= j 7)
                          (__f8 initial_1_trace)
                          (ite (= j 8) (__f9 initial_1_trace) a!1)))))
     (let ((a!3 (ite (= j 3)
                     (__f4 initial_1_trace)
                     (ite (= j 4)
                          (__f5 initial_1_trace)
                          (ite (= j 5) (__f6 initial_1_trace) a!2)))))
     (let ((a!4 (ite (= j 0)
                     (__f1 initial_1_trace)
                     (ite (= j 1)
                          (__f2 initial_1_trace)
                          (ite (= j 2) (__f3 initial_1_trace) a!3)))))
       (or (not (and (>= j 0) (<= j 9))) (= (__f1 a!4) NULL) a!5)))))
     :skolemid _skolem_2
     :qid _forall_2)))
(assert (forall ((i Int))
  (! (let ((a!1 (ite (= i 9)
                     (__f10 initial_1_trace)
                     (_tuple_2 NULL false (_tuple_1 (_tuple_0 0 INF) 0)))))
     (let ((a!2 (ite (= i 6)
                     (__f7 initial_1_trace)
                     (ite (= i 7)
                          (__f8 initial_1_trace)
                          (ite (= i 8) (__f9 initial_1_trace) a!1)))))
     (let ((a!3 (ite (= i 3)
                     (__f4 initial_1_trace)
                     (ite (= i 4)
                          (__f5 initial_1_trace)
                          (ite (= i 5) (__f6 initial_1_trace) a!2)))))
     (let ((a!4 (ite (= i 0)
                     (__f1 initial_1_trace)
                     (ite (= i 1)
                          (__f2 initial_1_trace)
                          (ite (= i 2) (__f3 initial_1_trace) a!3)))))
     (let ((a!5 (= (__f2 (__f1 (__f3 a!4))) SEC))
           (a!6 (* 1000 (__f1 (__f1 (__f3 a!4)))))
           (a!8 (not (<= (__f2 (__f3 a!4)) 0))))
     (let ((a!7 (__f1 (ite a!5 (_tuple_0 a!6 MSEC) (__f1 (__f3 a!4)))))
           (a!10 (= (ite a!5 (_tuple_0 a!6 MSEC) (__f1 (__f3 a!4)))
                    (_tuple_0 0 MSEC))))
     (let ((a!9 (not (or (not (<= a!7 0)) (and (= a!7 0) a!8))))
           (a!11 (and a!10 (= (__f2 (__f3 a!4)) 0))))
       (or (not (and (>= i 0) (<= i 9))) (not (and a!9 (not a!11)))))))))))
     :skolemid _skolem_3
     :qid _forall_3)))
(assert (let ((a!1 (forall ((v Int))
             (! (let ((a!1 (not (exists ((u Int))
                                  (! (let ((a!1 (ite (= u 9)
                                                     (__f10 initial_1_trace)
                                                     (_tuple_2 NULL
                                                               false
                                                               (_tuple_1 (_tuple_0 0
                                                                                   INF)
                                                                         0))))
                                           (a!8 (ite (= v 9)
                                                     (__f10 initial_1_trace)
                                                     (_tuple_2 NULL
                                                               false
                                                               (_tuple_1 (_tuple_0 0
                                                                                   INF)
                                                                         0)))))
                                     (let ((a!2 (ite (= u 6)
                                                     (__f7 initial_1_trace)
                                                     (ite (= u 7)
                                                          (__f8 initial_1_trace)
                                                          (ite (= u 8)
                                                               (__f9 initial_1_trace)
                                                               a!1))))
                                           (a!9 (ite (= v 6)
                                                     (__f7 initial_1_trace)
                                                     (ite (= v 7)
                                                          (__f8 initial_1_trace)
                                                          (ite (= v 8)
                                                               (__f9 initial_1_trace)
                                                               a!8)))))
                                     (let ((a!3 (ite (= u 3)
                                                     (__f4 initial_1_trace)
                                                     (ite (= u 4)
                                                          (__f5 initial_1_trace)
                                                          (ite (= u 5)
                                                               (__f6 initial_1_trace)
                                                               a!2))))
                                           (a!10 (ite (= v 3)
                                                      (__f4 initial_1_trace)
                                                      (ite (= v 4)
                                                           (__f5 initial_1_trace)
                                                           (ite (= v 5)
                                                                (__f6 initial_1_trace)
                                                                a!9)))))
                                     (let ((a!4 (ite (= u 0)
                                                     (__f1 initial_1_trace)
                                                     (ite (= u 1)
                                                          (__f2 initial_1_trace)
                                                          (ite (= u 2)
                                                               (__f3 initial_1_trace)
                                                               a!3))))
                                           (a!11 (ite (= v 0)
                                                      (__f1 initial_1_trace)
                                                      (ite (= v 1)
                                                           (__f2 initial_1_trace)
                                                           (ite (= v 2)
                                                                (__f3 initial_1_trace)
                                                                a!10)))))
                                     (let ((a!5 (= (__f2 (__f1 (__f3 a!4))) SEC))
                                           (a!6 (* 1000
                                                   (__f1 (__f1 (__f3 a!4)))))
                                           (a!12 (= (__f2 (__f1 (__f3 a!11)))
                                                    SEC))
                                           (a!13 (* 1000
                                                    (__f1 (__f1 (__f3 a!11)))))
                                           (a!15 (not (<= (__f2 (__f3 a!4))
                                                          (__f2 (__f3 a!11)))))
                                           (a!16 (= (__f2 (__f1 (__f3 a!4)))
                                                    INF))
                                           (a!17 (= (__f2 (__f1 (__f3 a!11)))
                                                    INF)))
                                     (let ((a!7 (__f1 (ite a!5
                                                           (_tuple_0 a!6 MSEC)
                                                           (__f1 (__f3 a!4)))))
                                           (a!14 (__f1 (ite a!12
                                                            (_tuple_0 a!13 MSEC)
                                                            (__f1 (__f3 a!11)))))
                                           (a!19 (= (ite a!5
                                                         (_tuple_0 a!6 MSEC)
                                                         (__f1 (__f3 a!4)))
                                                    (ite a!12
                                                         (_tuple_0 a!13 MSEC)
                                                         (__f1 (__f3 a!11))))))
                                     (let ((a!18 (not (or (not (<= a!7 a!14))
                                                          (and (= a!7 a!14)
                                                               a!15)
                                                          (and (not a!16) a!17))))
                                           (a!20 (and a!19
                                                      (= (__f2 (__f3 a!4))
                                                         (__f2 (__f3 a!11))))))
                                       (and (>= u 0) (<= u 9) a!18 (not a!20)))))))))
                                     :skolemid _skolem_4
                                     :qid _exists_0))))
                      (a!2 (ite (= v 9)
                                (__f10 initial_1_trace)
                                (_tuple_2 NULL
                                          false
                                          (_tuple_1 (_tuple_0 0 INF) 0)))))
                (let ((a!3 (ite (= v 6)
                                (__f7 initial_1_trace)
                                (ite (= v 7)
                                     (__f8 initial_1_trace)
                                     (ite (= v 8) (__f9 initial_1_trace) a!2)))))
                (let ((a!4 (ite (= v 3)
                                (__f4 initial_1_trace)
                                (ite (= v 4)
                                     (__f5 initial_1_trace)
                                     (ite (= v 5) (__f6 initial_1_trace) a!3)))))
                (let ((a!5 (ite (= v 0)
                                (__f1 initial_1_trace)
                                (ite (= v 1)
                                     (__f2 initial_1_trace)
                                     (ite (= v 2) (__f3 initial_1_trace) a!4)))))
                  (or (not (and (>= v 0) (<= v 9)))
                      (= a!1 (= (__f1 a!5) STARTUP)))))))
                :skolemid _skolem_5
                :qid _forall_4)))
      (a!2 (forall ((u Int))
             (! (let ((a!1 (ite (= u 9)
                                (__f10 initial_1_trace)
                                (_tuple_2 NULL
                                          false
                                          (_tuple_1 (_tuple_0 0 INF) 0))))
                      (a!5 (exists ((v Int))
                             (! (let ((a!1 (ite (= v 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0))))
                                      (a!7 (ite (= u 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0)))))
                                (let ((a!2 (ite (= v 6)
                                                (__f7 initial_1_trace)
                                                (ite (= v 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= v 8)
                                                          (__f9 initial_1_trace)
                                                          a!1))))
                                      (a!8 (ite (= u 6)
                                                (__f7 initial_1_trace)
                                                (ite (= u 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= u 8)
                                                          (__f9 initial_1_trace)
                                                          a!7)))))
                                (let ((a!3 (ite (= v 3)
                                                (__f4 initial_1_trace)
                                                (ite (= v 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= v 5)
                                                          (__f6 initial_1_trace)
                                                          a!2))))
                                      (a!9 (ite (= u 3)
                                                (__f4 initial_1_trace)
                                                (ite (= u 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= u 5)
                                                          (__f6 initial_1_trace)
                                                          a!8)))))
                                (let ((a!4 (ite (= v 0)
                                                (__f1 initial_1_trace)
                                                (ite (= v 1)
                                                     (__f2 initial_1_trace)
                                                     (ite (= v 2)
                                                          (__f3 initial_1_trace)
                                                          a!3))))
                                      (a!10 (ite (= u 0)
                                                 (__f1 initial_1_trace)
                                                 (ite (= u 1)
                                                      (__f2 initial_1_trace)
                                                      (ite (= u 2)
                                                           (__f3 initial_1_trace)
                                                           a!9)))))
                                (let ((a!5 (= (__f2 (__f1 (__f3 a!4))) SEC))
                                      (a!6 (* 1000 (__f1 (__f1 (__f3 a!4)))))
                                      (a!11 (= (__f2 (__f1 (__f3 a!10))) SEC))
                                      (a!12 (* 1000 (__f1 (__f1 (__f3 a!10))))))
                                (let ((a!13 (= (ite a!5
                                                    (_tuple_0 a!6 MSEC)
                                                    (__f1 (__f3 a!4)))
                                               (ite a!11
                                                    (_tuple_0 a!12 MSEC)
                                                    (__f1 (__f3 a!10))))))
                                  (and (>= v 0)
                                       (<= v 9)
                                       a!13
                                       (= (__f2 (__f3 a!4)) (__f2 (__f3 a!10)))
                                       (= (__f1 a!4) A1))))))))
                                :skolemid _skolem_6
                                :qid _exists_1)))
                      (a!7 (exists ((_i Int))
                             (! (let ((a!1 (ite (= _i 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0))))
                                      (a!5 (ite (= u 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0)))))
                                (let ((a!2 (ite (= _i 6)
                                                (__f7 initial_1_trace)
                                                (ite (= _i 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= _i 8)
                                                          (__f9 initial_1_trace)
                                                          a!1))))
                                      (a!6 (ite (= u 6)
                                                (__f7 initial_1_trace)
                                                (ite (= u 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= u 8)
                                                          (__f9 initial_1_trace)
                                                          a!5)))))
                                (let ((a!3 (ite (= _i 3)
                                                (__f4 initial_1_trace)
                                                (ite (= _i 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= _i 5)
                                                          (__f6 initial_1_trace)
                                                          a!2))))
                                      (a!7 (ite (= u 3)
                                                (__f4 initial_1_trace)
                                                (ite (= u 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= u 5)
                                                          (__f6 initial_1_trace)
                                                          a!6)))))
                                (let ((a!4 (ite (= _i 0)
                                                (__f1 initial_1_trace)
                                                (ite (= _i 1)
                                                     (__f2 initial_1_trace)
                                                     (ite (= _i 2)
                                                          (__f3 initial_1_trace)
                                                          a!3))))
                                      (a!8 (ite (= u 0)
                                                (__f1 initial_1_trace)
                                                (ite (= u 1)
                                                     (__f2 initial_1_trace)
                                                     (ite (= u 2)
                                                          (__f3 initial_1_trace)
                                                          a!7)))))
                                  (and (>= _i 0)
                                       (<= _i 9)
                                       (= (__f1 a!4) A_out)
                                       (__f2 a!4)
                                       (= (__f3 a!4) (__f3 a!8)))))))
                                :skolemid _skolem_7
                                :qid _exists_2))))
                (let ((a!2 (ite (= u 6)
                                (__f7 initial_1_trace)
                                (ite (= u 7)
                                     (__f8 initial_1_trace)
                                     (ite (= u 8) (__f9 initial_1_trace) a!1)))))
                (let ((a!3 (ite (= u 3)
                                (__f4 initial_1_trace)
                                (ite (= u 4)
                                     (__f5 initial_1_trace)
                                     (ite (= u 5) (__f6 initial_1_trace) a!2)))))
                (let ((a!4 (ite (= u 0)
                                (__f1 initial_1_trace)
                                (ite (= u 1)
                                     (__f2 initial_1_trace)
                                     (ite (= u 2) (__f3 initial_1_trace) a!3)))))
                (let ((a!6 (or (not (= (__f1 a!4) STARTUP)) a!5))
                      (a!8 (or (not (= (__f1 a!4) A1)) a!7)))
                  (or (not (and (>= u (- 1)) (<= u 8))) (and a!6 a!8)))))))
                :skolemid _skolem_8
                :qid _forall_5)))
      (a!3 (forall ((u Int))
             (! (let ((a!1 (forall ((_i Int))
                             (! (let ((a!1 (ite (= _i 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0))))
                                      (a!5 (ite (= u 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0))))
                                      (a!10 (exists ((_j Int))
                                              (! (let ((a!1 (ite (= _j 9)
                                                                 (__f10 initial_1_trace)
                                                                 (_tuple_2 NULL
                                                                           false
                                                                           (_tuple_1 (_tuple_0 0
                                                                                               INF)
                                                                                     0))))
                                                       (a!5 (ite (= _i 9)
                                                                 (__f10 initial_1_trace)
                                                                 (_tuple_2 NULL
                                                                           false
                                                                           (_tuple_1 (_tuple_0 0
                                                                                               INF)
                                                                                     0)))))
                                                 (let ((a!2 (ite (= _j 6)
                                                                 (__f7 initial_1_trace)
                                                                 (ite (= _j 7)
                                                                      (__f8 initial_1_trace)
                                                                      (ite (= _j
                                                                              8)
                                                                           (__f9 initial_1_trace)
                                                                           a!1))))
                                                       (a!6 (ite (= _i 6)
                                                                 (__f7 initial_1_trace)
                                                                 (ite (= _i 7)
                                                                      (__f8 initial_1_trace)
                                                                      (ite (= _i
                                                                              8)
                                                                           (__f9 initial_1_trace)
                                                                           a!5)))))
                                                 (let ((a!3 (ite (= _j 3)
                                                                 (__f4 initial_1_trace)
                                                                 (ite (= _j 4)
                                                                      (__f5 initial_1_trace)
                                                                      (ite (= _j
                                                                              5)
                                                                           (__f6 initial_1_trace)
                                                                           a!2))))
                                                       (a!7 (ite (= _i 3)
                                                                 (__f4 initial_1_trace)
                                                                 (ite (= _i 4)
                                                                      (__f5 initial_1_trace)
                                                                      (ite (= _i
                                                                              5)
                                                                           (__f6 initial_1_trace)
                                                                           a!6)))))
                                                 (let ((a!4 (ite (= _j 0)
                                                                 (__f1 initial_1_trace)
                                                                 (ite (= _j 1)
                                                                      (__f2 initial_1_trace)
                                                                      (ite (= _j
                                                                              2)
                                                                           (__f3 initial_1_trace)
                                                                           a!3))))
                                                       (a!8 (ite (= _i 0)
                                                                 (__f1 initial_1_trace)
                                                                 (ite (= _i 1)
                                                                      (__f2 initial_1_trace)
                                                                      (ite (= _i
                                                                              2)
                                                                           (__f3 initial_1_trace)
                                                                           a!7)))))
                                                   (and (= (__f1 a!4) B_in)
                                                        (= (__f2 a!8)
                                                           (__f2 a!4))
                                                        (= (__f3 a!8)
                                                           (__f3 a!4)))))))
                                                 :skolemid _skolem_9
                                                 :qid _exists_3))))
                                (let ((a!2 (ite (= _i 6)
                                                (__f7 initial_1_trace)
                                                (ite (= _i 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= _i 8)
                                                          (__f9 initial_1_trace)
                                                          a!1))))
                                      (a!6 (ite (= u 6)
                                                (__f7 initial_1_trace)
                                                (ite (= u 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= u 8)
                                                          (__f9 initial_1_trace)
                                                          a!5)))))
                                (let ((a!3 (ite (= _i 3)
                                                (__f4 initial_1_trace)
                                                (ite (= _i 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= _i 5)
                                                          (__f6 initial_1_trace)
                                                          a!2))))
                                      (a!7 (ite (= u 3)
                                                (__f4 initial_1_trace)
                                                (ite (= u 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= u 5)
                                                          (__f6 initial_1_trace)
                                                          a!6)))))
                                (let ((a!4 (ite (= _i 0)
                                                (__f1 initial_1_trace)
                                                (ite (= _i 1)
                                                     (__f2 initial_1_trace)
                                                     (ite (= _i 2)
                                                          (__f3 initial_1_trace)
                                                          a!3))))
                                      (a!8 (ite (= u 0)
                                                (__f1 initial_1_trace)
                                                (ite (= u 1)
                                                     (__f2 initial_1_trace)
                                                     (ite (= u 2)
                                                          (__f3 initial_1_trace)
                                                          a!7)))))
                                (let ((a!9 (not (and (= (__f1 a!4) A_out)
                                                     (= (__f3 a!4) (__f3 a!8))))))
                                  (or (not (and (>= _i 0) (<= _i 9))) a!9 a!10))))))
                                :skolemid _skolem_10
                                :qid _forall_6))))
                  (or (not (and (>= u 0) (<= u 9))) a!1))
                :skolemid _skolem_11
                :qid _forall_7)))
      (a!4 (forall ((u Int))
             (! (let ((a!1 (ite (= u 9)
                                (__f10 initial_1_trace)
                                (_tuple_2 NULL
                                          false
                                          (_tuple_1 (_tuple_0 0 INF) 0))))
                      (a!5 (exists ((v Int))
                             (! (let ((a!1 (ite (= u 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0))))
                                      (a!6 (ite (= v 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0)))))
                                (let ((a!2 (ite (= u 6)
                                                (__f7 initial_1_trace)
                                                (ite (= u 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= u 8)
                                                          (__f9 initial_1_trace)
                                                          a!1))))
                                      (a!7 (ite (= v 6)
                                                (__f7 initial_1_trace)
                                                (ite (= v 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= v 8)
                                                          (__f9 initial_1_trace)
                                                          a!6)))))
                                (let ((a!3 (ite (= u 3)
                                                (__f4 initial_1_trace)
                                                (ite (= u 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= u 5)
                                                          (__f6 initial_1_trace)
                                                          a!2))))
                                      (a!8 (ite (= v 3)
                                                (__f4 initial_1_trace)
                                                (ite (= v 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= v 5)
                                                          (__f6 initial_1_trace)
                                                          a!7)))))
                                (let ((a!4 (ite (= u 0)
                                                (__f1 initial_1_trace)
                                                (ite (= u 1)
                                                     (__f2 initial_1_trace)
                                                     (ite (= u 2)
                                                          (__f3 initial_1_trace)
                                                          a!3))))
                                      (a!9 (ite (= v 0)
                                                (__f1 initial_1_trace)
                                                (ite (= v 1)
                                                     (__f2 initial_1_trace)
                                                     (ite (= v 2)
                                                          (__f3 initial_1_trace)
                                                          a!8)))))
                                (let ((a!5 (= (__f2 (__f1 (__f3 a!4))) INF))
                                      (a!10 (= (__f2 (__f1 (__f3 a!9))) INF))
                                      (a!11 (= (__f2 (__f1 (__f3 a!4))) SEC))
                                      (a!12 (* 1000 (__f1 (__f1 (__f3 a!4)))))
                                      (a!14 (= (__f2 (__f1 (__f3 a!9))) SEC))
                                      (a!15 (* 1000 (__f1 (__f1 (__f3 a!9)))))
                                      (a!17 (not (<= (__f2 (__f3 a!4))
                                                     (__f2 (__f3 a!9))))))
                                (let ((a!13 (__f1 (ite a!11
                                                       (_tuple_0 a!12 MSEC)
                                                       (__f1 (__f3 a!4)))))
                                      (a!16 (__f1 (ite a!14
                                                       (_tuple_0 a!15 MSEC)
                                                       (__f1 (__f3 a!9)))))
                                      (a!19 (= (ite a!11
                                                    (_tuple_0 a!12 MSEC)
                                                    (__f1 (__f3 a!4)))
                                               (ite a!14
                                                    (_tuple_0 a!15 MSEC)
                                                    (__f1 (__f3 a!9))))))
                                (let ((a!18 (not (or (and (not a!5) a!10)
                                                     (and (= a!13 a!16) a!17)
                                                     (not (<= a!13 a!16)))))
                                      (a!20 (and a!19
                                                 (= (__f2 (__f3 a!4))
                                                    (__f2 (__f3 a!9))))))
                                  (and (>= v 0)
                                       (<= v 9)
                                       a!18
                                       (not a!20)
                                       (= (__f1 a!9) B1)))))))))
                                :skolemid _skolem_12
                                :qid _exists_4)))
                      (a!7 (exists ((_i Int))
                             (! (let ((a!1 (ite (= _i 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0))))
                                      (a!5 (ite (= u 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0)))))
                                (let ((a!2 (ite (= _i 6)
                                                (__f7 initial_1_trace)
                                                (ite (= _i 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= _i 8)
                                                          (__f9 initial_1_trace)
                                                          a!1))))
                                      (a!6 (ite (= u 6)
                                                (__f7 initial_1_trace)
                                                (ite (= u 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= u 8)
                                                          (__f9 initial_1_trace)
                                                          a!5)))))
                                (let ((a!3 (ite (= _i 3)
                                                (__f4 initial_1_trace)
                                                (ite (= _i 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= _i 5)
                                                          (__f6 initial_1_trace)
                                                          a!2))))
                                      (a!7 (ite (= u 3)
                                                (__f4 initial_1_trace)
                                                (ite (= u 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= u 5)
                                                          (__f6 initial_1_trace)
                                                          a!6)))))
                                (let ((a!4 (ite (= _i 0)
                                                (__f1 initial_1_trace)
                                                (ite (= _i 1)
                                                     (__f2 initial_1_trace)
                                                     (ite (= _i 2)
                                                          (__f3 initial_1_trace)
                                                          a!3))))
                                      (a!8 (ite (= u 0)
                                                (__f1 initial_1_trace)
                                                (ite (= u 1)
                                                     (__f2 initial_1_trace)
                                                     (ite (= u 2)
                                                          (__f3 initial_1_trace)
                                                          a!7)))))
                                  (and (>= _i 0)
                                       (<= _i 9)
                                       (= (__f1 a!4) B_ramp_exists)
                                       (__f2 a!4)
                                       (= (__f3 a!4) (__f3 a!8)))))))
                                :skolemid _skolem_13
                                :qid _exists_5)))
                      (a!8 (forall ((_i Int))
                             (! (let ((a!1 (ite (= _i 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0))))
                                      (a!5 (ite (= u 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0))))
                                      (a!10 (exists ((_j Int))
                                              (! (let ((a!1 (ite (= _j 9)
                                                                 (__f10 initial_1_trace)
                                                                 (_tuple_2 NULL
                                                                           false
                                                                           (_tuple_1 (_tuple_0 0
                                                                                               INF)
                                                                                     0))))
                                                       (a!5 (ite (= _i 9)
                                                                 (__f10 initial_1_trace)
                                                                 (_tuple_2 NULL
                                                                           false
                                                                           (_tuple_1 (_tuple_0 0
                                                                                               INF)
                                                                                     0)))))
                                                 (let ((a!2 (ite (= _j 6)
                                                                 (__f7 initial_1_trace)
                                                                 (ite (= _j 7)
                                                                      (__f8 initial_1_trace)
                                                                      (ite (= _j
                                                                              8)
                                                                           (__f9 initial_1_trace)
                                                                           a!1))))
                                                       (a!6 (ite (= _i 6)
                                                                 (__f7 initial_1_trace)
                                                                 (ite (= _i 7)
                                                                      (__f8 initial_1_trace)
                                                                      (ite (= _i
                                                                              8)
                                                                           (__f9 initial_1_trace)
                                                                           a!5)))))
                                                 (let ((a!3 (ite (= _j 3)
                                                                 (__f4 initial_1_trace)
                                                                 (ite (= _j 4)
                                                                      (__f5 initial_1_trace)
                                                                      (ite (= _j
                                                                              5)
                                                                           (__f6 initial_1_trace)
                                                                           a!2))))
                                                       (a!7 (ite (= _i 3)
                                                                 (__f4 initial_1_trace)
                                                                 (ite (= _i 4)
                                                                      (__f5 initial_1_trace)
                                                                      (ite (= _i
                                                                              5)
                                                                           (__f6 initial_1_trace)
                                                                           a!6)))))
                                                 (let ((a!4 (ite (= _j 0)
                                                                 (__f1 initial_1_trace)
                                                                 (ite (= _j 1)
                                                                      (__f2 initial_1_trace)
                                                                      (ite (= _j
                                                                              2)
                                                                           (__f3 initial_1_trace)
                                                                           a!3))))
                                                       (a!8 (ite (= _i 0)
                                                                 (__f1 initial_1_trace)
                                                                 (ite (= _i 1)
                                                                      (__f2 initial_1_trace)
                                                                      (ite (= _i
                                                                              2)
                                                                           (__f3 initial_1_trace)
                                                                           a!7)))))
                                                   (and (= (__f1 a!4) B_out)
                                                        (= (__f2 a!8)
                                                           (__f2 a!4))
                                                        (= (__f3 a!8)
                                                           (__f3 a!4)))))))
                                                 :skolemid _skolem_14
                                                 :qid _exists_6))))
                                (let ((a!2 (ite (= _i 6)
                                                (__f7 initial_1_trace)
                                                (ite (= _i 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= _i 8)
                                                          (__f9 initial_1_trace)
                                                          a!1))))
                                      (a!6 (ite (= u 6)
                                                (__f7 initial_1_trace)
                                                (ite (= u 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= u 8)
                                                          (__f9 initial_1_trace)
                                                          a!5)))))
                                (let ((a!3 (ite (= _i 3)
                                                (__f4 initial_1_trace)
                                                (ite (= _i 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= _i 5)
                                                          (__f6 initial_1_trace)
                                                          a!2))))
                                      (a!7 (ite (= u 3)
                                                (__f4 initial_1_trace)
                                                (ite (= u 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= u 5)
                                                          (__f6 initial_1_trace)
                                                          a!6)))))
                                (let ((a!4 (ite (= _i 0)
                                                (__f1 initial_1_trace)
                                                (ite (= _i 1)
                                                     (__f2 initial_1_trace)
                                                     (ite (= _i 2)
                                                          (__f3 initial_1_trace)
                                                          a!3))))
                                      (a!8 (ite (= u 0)
                                                (__f1 initial_1_trace)
                                                (ite (= u 1)
                                                     (__f2 initial_1_trace)
                                                     (ite (= u 2)
                                                          (__f3 initial_1_trace)
                                                          a!7)))))
                                (let ((a!9 (not (and (= (__f1 a!4) B_in)
                                                     (= (__f3 a!4) (__f3 a!8))))))
                                  (or (not (and (>= _i 0) (<= _i 9))) a!9 a!10))))))
                                :skolemid _skolem_15
                                :qid _forall_8))))
                (let ((a!2 (ite (= u 6)
                                (__f7 initial_1_trace)
                                (ite (= u 7)
                                     (__f8 initial_1_trace)
                                     (ite (= u 8) (__f9 initial_1_trace) a!1)))))
                (let ((a!3 (ite (= u 3)
                                (__f4 initial_1_trace)
                                (ite (= u 4)
                                     (__f5 initial_1_trace)
                                     (ite (= u 5) (__f6 initial_1_trace) a!2)))))
                (let ((a!4 (ite (= u 0)
                                (__f1 initial_1_trace)
                                (ite (= u 1)
                                     (__f2 initial_1_trace)
                                     (ite (= u 2) (__f3 initial_1_trace) a!3)))))
                (let ((a!6 (or (not (= (__f1 a!4) B_in)) a!5))
                      (a!9 (or (not (= (__f1 a!4) B1)) (not a!7) a!8)))
                  (or (not (and (>= u 0) (<= u 9))) (and a!6 a!9)))))))
                :skolemid _skolem_16
                :qid _forall_9)))
      (a!5 (forall ((u Int))
             (! (let ((a!1 (forall ((_i Int))
                             (! (let ((a!1 (ite (= _i 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0))))
                                      (a!5 (ite (= u 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0))))
                                      (a!10 (exists ((_j Int))
                                              (! (let ((a!1 (ite (= _j 9)
                                                                 (__f10 initial_1_trace)
                                                                 (_tuple_2 NULL
                                                                           false
                                                                           (_tuple_1 (_tuple_0 0
                                                                                               INF)
                                                                                     0))))
                                                       (a!5 (ite (= _i 9)
                                                                 (__f10 initial_1_trace)
                                                                 (_tuple_2 NULL
                                                                           false
                                                                           (_tuple_1 (_tuple_0 0
                                                                                               INF)
                                                                                     0)))))
                                                 (let ((a!2 (ite (= _j 6)
                                                                 (__f7 initial_1_trace)
                                                                 (ite (= _j 7)
                                                                      (__f8 initial_1_trace)
                                                                      (ite (= _j
                                                                              8)
                                                                           (__f9 initial_1_trace)
                                                                           a!1))))
                                                       (a!6 (ite (= _i 6)
                                                                 (__f7 initial_1_trace)
                                                                 (ite (= _i 7)
                                                                      (__f8 initial_1_trace)
                                                                      (ite (= _i
                                                                              8)
                                                                           (__f9 initial_1_trace)
                                                                           a!5)))))
                                                 (let ((a!3 (ite (= _j 3)
                                                                 (__f4 initial_1_trace)
                                                                 (ite (= _j 4)
                                                                      (__f5 initial_1_trace)
                                                                      (ite (= _j
                                                                              5)
                                                                           (__f6 initial_1_trace)
                                                                           a!2))))
                                                       (a!7 (ite (= _i 3)
                                                                 (__f4 initial_1_trace)
                                                                 (ite (= _i 4)
                                                                      (__f5 initial_1_trace)
                                                                      (ite (= _i
                                                                              5)
                                                                           (__f6 initial_1_trace)
                                                                           a!6)))))
                                                 (let ((a!4 (ite (= _j 0)
                                                                 (__f1 initial_1_trace)
                                                                 (ite (= _j 1)
                                                                      (__f2 initial_1_trace)
                                                                      (ite (= _j
                                                                              2)
                                                                           (__f3 initial_1_trace)
                                                                           a!3))))
                                                       (a!8 (ite (= _i 0)
                                                                 (__f1 initial_1_trace)
                                                                 (ite (= _i 1)
                                                                      (__f2 initial_1_trace)
                                                                      (ite (= _i
                                                                              2)
                                                                           (__f3 initial_1_trace)
                                                                           a!7)))))
                                                   (and (= (__f1 a!4) C_in)
                                                        (= (__f2 a!8)
                                                           (__f2 a!4))
                                                        (= (__f3 a!8)
                                                           (__f3 a!4)))))))
                                                 :skolemid _skolem_17
                                                 :qid _exists_7))))
                                (let ((a!2 (ite (= _i 6)
                                                (__f7 initial_1_trace)
                                                (ite (= _i 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= _i 8)
                                                          (__f9 initial_1_trace)
                                                          a!1))))
                                      (a!6 (ite (= u 6)
                                                (__f7 initial_1_trace)
                                                (ite (= u 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= u 8)
                                                          (__f9 initial_1_trace)
                                                          a!5)))))
                                (let ((a!3 (ite (= _i 3)
                                                (__f4 initial_1_trace)
                                                (ite (= _i 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= _i 5)
                                                          (__f6 initial_1_trace)
                                                          a!2))))
                                      (a!7 (ite (= u 3)
                                                (__f4 initial_1_trace)
                                                (ite (= u 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= u 5)
                                                          (__f6 initial_1_trace)
                                                          a!6)))))
                                (let ((a!4 (ite (= _i 0)
                                                (__f1 initial_1_trace)
                                                (ite (= _i 1)
                                                     (__f2 initial_1_trace)
                                                     (ite (= _i 2)
                                                          (__f3 initial_1_trace)
                                                          a!3))))
                                      (a!8 (ite (= u 0)
                                                (__f1 initial_1_trace)
                                                (ite (= u 1)
                                                     (__f2 initial_1_trace)
                                                     (ite (= u 2)
                                                          (__f3 initial_1_trace)
                                                          a!7)))))
                                (let ((a!9 (not (and (= (__f1 a!4) B_out)
                                                     (= (__f3 a!4) (__f3 a!8))))))
                                  (or (not (and (>= _i 0) (<= _i 9))) a!9 a!10))))))
                                :skolemid _skolem_18
                                :qid _forall_10))))
                  (or (not (and (>= u 0) (<= u 9))) a!1))
                :skolemid _skolem_19
                :qid _forall_11)))
      (a!6 (forall ((u Int))
             (! (let ((a!1 (ite (= u 9)
                                (__f10 initial_1_trace)
                                (_tuple_2 NULL
                                          false
                                          (_tuple_1 (_tuple_0 0 INF) 0))))
                      (a!5 (exists ((v Int))
                             (! (let ((a!1 (ite (= u 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0))))
                                      (a!6 (ite (= v 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0)))))
                                (let ((a!2 (ite (= u 6)
                                                (__f7 initial_1_trace)
                                                (ite (= u 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= u 8)
                                                          (__f9 initial_1_trace)
                                                          a!1))))
                                      (a!7 (ite (= v 6)
                                                (__f7 initial_1_trace)
                                                (ite (= v 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= v 8)
                                                          (__f9 initial_1_trace)
                                                          a!6)))))
                                (let ((a!3 (ite (= u 3)
                                                (__f4 initial_1_trace)
                                                (ite (= u 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= u 5)
                                                          (__f6 initial_1_trace)
                                                          a!2))))
                                      (a!8 (ite (= v 3)
                                                (__f4 initial_1_trace)
                                                (ite (= v 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= v 5)
                                                          (__f6 initial_1_trace)
                                                          a!7)))))
                                (let ((a!4 (ite (= u 0)
                                                (__f1 initial_1_trace)
                                                (ite (= u 1)
                                                     (__f2 initial_1_trace)
                                                     (ite (= u 2)
                                                          (__f3 initial_1_trace)
                                                          a!3))))
                                      (a!9 (ite (= v 0)
                                                (__f1 initial_1_trace)
                                                (ite (= v 1)
                                                     (__f2 initial_1_trace)
                                                     (ite (= v 2)
                                                          (__f3 initial_1_trace)
                                                          a!8)))))
                                (let ((a!5 (= (__f2 (__f1 (__f3 a!4))) INF))
                                      (a!10 (= (__f2 (__f1 (__f3 a!9))) INF))
                                      (a!11 (= (__f2 (__f1 (__f3 a!4))) SEC))
                                      (a!12 (* 1000 (__f1 (__f1 (__f3 a!4)))))
                                      (a!14 (= (__f2 (__f1 (__f3 a!9))) SEC))
                                      (a!15 (* 1000 (__f1 (__f1 (__f3 a!9)))))
                                      (a!17 (not (<= (__f2 (__f3 a!4))
                                                     (__f2 (__f3 a!9))))))
                                (let ((a!13 (__f1 (ite a!11
                                                       (_tuple_0 a!12 MSEC)
                                                       (__f1 (__f3 a!4)))))
                                      (a!16 (__f1 (ite a!14
                                                       (_tuple_0 a!15 MSEC)
                                                       (__f1 (__f3 a!9)))))
                                      (a!19 (= (ite a!11
                                                    (_tuple_0 a!12 MSEC)
                                                    (__f1 (__f3 a!4)))
                                               (ite a!14
                                                    (_tuple_0 a!15 MSEC)
                                                    (__f1 (__f3 a!9))))))
                                (let ((a!18 (not (or (and (not a!5) a!10)
                                                     (and (= a!13 a!16) a!17)
                                                     (not (<= a!13 a!16)))))
                                      (a!20 (and a!19
                                                 (= (__f2 (__f3 a!4))
                                                    (__f2 (__f3 a!9))))))
                                  (and (>= v 0)
                                       (<= v 9)
                                       a!18
                                       (not a!20)
                                       (= (__f1 a!9) C1)))))))))
                                :skolemid _skolem_20
                                :qid _exists_8)))
                      (a!7 (forall ((_i Int))
                             (! (let ((a!1 (ite (= _i 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0))))
                                      (a!5 (ite (= u 9)
                                                (__f10 initial_1_trace)
                                                (_tuple_2 NULL
                                                          false
                                                          (_tuple_1 (_tuple_0 0
                                                                              INF)
                                                                    0))))
                                      (a!10 (exists ((_j Int))
                                              (! (let ((a!1 (ite (= _j 9)
                                                                 (__f10 initial_1_trace)
                                                                 (_tuple_2 NULL
                                                                           false
                                                                           (_tuple_1 (_tuple_0 0
                                                                                               INF)
                                                                                     0))))
                                                       (a!5 (ite (= _i 9)
                                                                 (__f10 initial_1_trace)
                                                                 (_tuple_2 NULL
                                                                           false
                                                                           (_tuple_1 (_tuple_0 0
                                                                                               INF)
                                                                                     0)))))
                                                 (let ((a!2 (ite (= _j 6)
                                                                 (__f7 initial_1_trace)
                                                                 (ite (= _j 7)
                                                                      (__f8 initial_1_trace)
                                                                      (ite (= _j
                                                                              8)
                                                                           (__f9 initial_1_trace)
                                                                           a!1))))
                                                       (a!6 (ite (= _i 6)
                                                                 (__f7 initial_1_trace)
                                                                 (ite (= _i 7)
                                                                      (__f8 initial_1_trace)
                                                                      (ite (= _i
                                                                              8)
                                                                           (__f9 initial_1_trace)
                                                                           a!5)))))
                                                 (let ((a!3 (ite (= _j 3)
                                                                 (__f4 initial_1_trace)
                                                                 (ite (= _j 4)
                                                                      (__f5 initial_1_trace)
                                                                      (ite (= _j
                                                                              5)
                                                                           (__f6 initial_1_trace)
                                                                           a!2))))
                                                       (a!7 (ite (= _i 3)
                                                                 (__f4 initial_1_trace)
                                                                 (ite (= _i 4)
                                                                      (__f5 initial_1_trace)
                                                                      (ite (= _i
                                                                              5)
                                                                           (__f6 initial_1_trace)
                                                                           a!6)))))
                                                 (let ((a!4 (ite (= _j 0)
                                                                 (__f1 initial_1_trace)
                                                                 (ite (= _j 1)
                                                                      (__f2 initial_1_trace)
                                                                      (ite (= _j
                                                                              2)
                                                                           (__f3 initial_1_trace)
                                                                           a!3))))
                                                       (a!8 (ite (= _i 0)
                                                                 (__f1 initial_1_trace)
                                                                 (ite (= _i 1)
                                                                      (__f2 initial_1_trace)
                                                                      (ite (= _i
                                                                              2)
                                                                           (__f3 initial_1_trace)
                                                                           a!7)))))
                                                   (and (= (__f1 a!4) C_s)
                                                        (= (__f2 a!8)
                                                           (__f2 a!4))
                                                        (= (__f3 a!8)
                                                           (__f3 a!4)))))))
                                                 :skolemid _skolem_21
                                                 :qid _exists_9))))
                                (let ((a!2 (ite (= _i 6)
                                                (__f7 initial_1_trace)
                                                (ite (= _i 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= _i 8)
                                                          (__f9 initial_1_trace)
                                                          a!1))))
                                      (a!6 (ite (= u 6)
                                                (__f7 initial_1_trace)
                                                (ite (= u 7)
                                                     (__f8 initial_1_trace)
                                                     (ite (= u 8)
                                                          (__f9 initial_1_trace)
                                                          a!5)))))
                                (let ((a!3 (ite (= _i 3)
                                                (__f4 initial_1_trace)
                                                (ite (= _i 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= _i 5)
                                                          (__f6 initial_1_trace)
                                                          a!2))))
                                      (a!7 (ite (= u 3)
                                                (__f4 initial_1_trace)
                                                (ite (= u 4)
                                                     (__f5 initial_1_trace)
                                                     (ite (= u 5)
                                                          (__f6 initial_1_trace)
                                                          a!6)))))
                                (let ((a!4 (ite (= _i 0)
                                                (__f1 initial_1_trace)
                                                (ite (= _i 1)
                                                     (__f2 initial_1_trace)
                                                     (ite (= _i 2)
                                                          (__f3 initial_1_trace)
                                                          a!3))))
                                      (a!8 (ite (= u 0)
                                                (__f1 initial_1_trace)
                                                (ite (= u 1)
                                                     (__f2 initial_1_trace)
                                                     (ite (= u 2)
                                                          (__f3 initial_1_trace)
                                                          a!7)))))
                                (let ((a!9 (not (and (= (__f1 a!4) C_in)
                                                     (= (__f3 a!4) (__f3 a!8))))))
                                  (or (not (and (>= _i 0) (<= _i 9))) a!9 a!10))))))
                                :skolemid _skolem_22
                                :qid _forall_12))))
                (let ((a!2 (ite (= u 6)
                                (__f7 initial_1_trace)
                                (ite (= u 7)
                                     (__f8 initial_1_trace)
                                     (ite (= u 8) (__f9 initial_1_trace) a!1)))))
                (let ((a!3 (ite (= u 3)
                                (__f4 initial_1_trace)
                                (ite (= u 4)
                                     (__f5 initial_1_trace)
                                     (ite (= u 5) (__f6 initial_1_trace) a!2)))))
                (let ((a!4 (ite (= u 0)
                                (__f1 initial_1_trace)
                                (ite (= u 1)
                                     (__f2 initial_1_trace)
                                     (ite (= u 2) (__f3 initial_1_trace) a!3)))))
                (let ((a!6 (or (not (= (__f1 a!4) C_in)) a!5))
                      (a!8 (or (not (= (__f1 a!4) C1)) a!7)))
                  (or (not (and (>= u 0) (<= u 9))) (and a!6 a!8)))))))
                :skolemid _skolem_23
                :qid _forall_13)))
      (a!7 (exists ((x Int))
             (! (let ((a!1 (ite (= x 9)
                                (__f10 initial_1_trace)
                                (_tuple_2 NULL
                                          false
                                          (_tuple_1 (_tuple_0 0 INF) 0)))))
                (let ((a!2 (ite (= x 6)
                                (__f7 initial_1_trace)
                                (ite (= x 7)
                                     (__f8 initial_1_trace)
                                     (ite (= x 8) (__f9 initial_1_trace) a!1)))))
                (let ((a!3 (ite (= x 3)
                                (__f4 initial_1_trace)
                                (ite (= x 4)
                                     (__f5 initial_1_trace)
                                     (ite (= x 5) (__f6 initial_1_trace) a!2)))))
                (let ((a!4 (ite (= x 0)
                                (__f1 initial_1_trace)
                                (ite (= x 1)
                                     (__f2 initial_1_trace)
                                     (ite (= x 2) (__f3 initial_1_trace) a!3)))))
                (let ((a!5 (= (__f2 (__f1 (__f3 a!4))) SEC))
                      (a!6 (* 1000 (__f1 (__f1 (__f3 a!4)))))
                      (a!8 (not (<= (__f2 (__f3 a!4)) 0))))
                (let ((a!7 (__f1 (ite a!5 (_tuple_0 a!6 MSEC) (__f1 (__f3 a!4)))))
                      (a!10 (= (ite a!5 (_tuple_0 a!6 MSEC) (__f1 (__f3 a!4)))
                               (_tuple_0 0 MSEC))))
                (let ((a!9 (not (or (not (<= a!7 0)) (and (= a!7 0) a!8))))
                      (a!11 (and a!10 (= (__f2 (__f3 a!4)) 0))))
                  (and (>= x 0)
                       (<= x 9)
                       (not (and a!9 (not a!11)))
                       (= (__f1 a!4) C_s)
                       (__f2 a!4)))))))))
                :skolemid _skolem_24
                :qid _exists_10))))
  (not (or (not (and a!1 a!2 a!3 a!4 a!5 a!6)) a!7))))


(check-sat)
(get-info :all-statistics)
(get-model)
